/**
 * clangd_glued_preamble.h — IDE-only preamble for historical glued TU layout.
 *
 * wave309 honesty: compiler/ast_pool.c / pipeline_glue.c / ast_pool_bootstrap_glue.c
 * were deleted (structure-floor leave). They are NOT live #include sources into
 * pipeline_gen.c anymore. Live pool/arena/regalloc authority =
 * compiler/src/runtime_pipeline_abi.x (+ pipeline.x / backend seed).
 *
 * This header remains so clangd can still open residual IDE/type snapshots via
 * .clangd -include and ide/pipeline_glue_types.inc (generated by
 * scripts/gen_compile_commands.sh). Do not treat filenames below as product
 * compile inputs.
 *
 * PLATFORM: SHARED archaeology / IDE hygiene only (not on product link path).
 */
#ifndef CLANGD_GLUED_PREAMBLE_H
#define CLANGD_GLUED_PREAMBLE_H

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

/** Slice shape historically used by glue helpers; live ABI owns freestanding twins. */
struct xlang_slice_uint8_t {
  uint8_t *data;
  size_t length;
};

#if __has_include("pipeline_glue_types.inc")
#include "pipeline_glue_types.inc"
#else
#warning "Run: ./compiler/scripts/gen_compile_commands.sh (generates ide/pipeline_glue_types.inc)"
#endif

/**
 * Forward decls for IDE when opening residual bootstrap-glue fossils / type
 * snapshots. Live strong bodies: runtime_pipeline_abi (ast_pool.c /
 * pipeline_glue.c left wave309). IDE-only — not a product compile surface.
 */
extern int32_t asm_bump_off_before_struct_local(struct ast_ASTArena *arena, int32_t type_ref, int32_t off);
extern int32_t asm_local_slot_bytes(struct ast_ASTArena *arena, int32_t type_ref);
extern int32_t asm_type_is_simd_vector_spelling(struct ast_ASTArena *arena, int32_t type_ref);
extern int32_t pipeline_type_kind_ord_at(struct ast_ASTArena *arena, int32_t type_ref);
extern struct ast_Type *pipeline_arena_type_ptr(struct ast_ASTArena *a, int32_t ref);

#endif /* CLANGD_GLUED_PREAMBLE_H */
