#!/bin/sh
# cc_inc_tu.sh — compile one TU from .inc / seed .c (G-02e-15 thin alias)
#
# Usage (from compiler/):
#   sh scripts/cc_inc_tu.sh <rel-or-abs.inc|.c> <out.o> [extra cc flags...]
#
# Writes a temporary wrap.c that #includes the absolute source path, runs
# cc -c, then removes the wrap.
#
# wave831 (G.7 有则补全; not physical delete):
#   Makefile residual leaves use FORCE + this script only (no seed make-graph
#   prereq). Shell owns freshness:
#     - skip when OUT exists and is newer than INC and optional peers
#     - XLANG_CC_INC_TU_PEERS: space-separated extra inputs (.x, twin .c, …)
#     - XLANG_CC_INC_TU_FORCE=1: always recompile
#   PLATFORM: SHARED — cheap mtime skip on every FORCE recipe run.
set -e
cd "$(dirname "$0")/.."

if [ "$#" -lt 2 ]; then
  echo "usage: cc_inc_tu.sh <file.inc> <out.o> [extra cflags...]" >&2
  exit 2
fi

INC="$1"
OUT="$2"
shift 2

case "$INC" in
  /*) INC_ABS="$INC" ;;
  *) INC_ABS="$(pwd)/$INC" ;;
esac

# Why: On Windows MSYS/MinGW, `pwd` returns Unix-style /c/Users/... paths
#      which Windows gcc cannot resolve inside `#include "/c/Users/..."`.
#      cygpath -m converts to mixed-mode C:/Users/... that Windows gcc
#      accepts (forward slashes + drive letter).
# Invariant: cygpath exists ONLY under MSYS/Cygwin; on Linux/macOS the
#            if-branch is skipped and INC_ABS stays POSIX-style (no-op).
# PLATFORM: SHARED (Windows branch only).
if command -v cygpath >/dev/null 2>&1; then
  INC_ABS="$(cygpath -m "$INC_ABS")"
fi

if [ ! -f "$INC_ABS" ]; then
  echo "cc_inc_tu: missing $INC_ABS" >&2
  exit 1
fi

# wave831: FORCE recipes always enter this script; skip rebuild when fresh.
# Peers (optional): e.g. matching .x beside a seed.from_x.c.
# PLATFORM: SHARED.
if [ -z "${XLANG_CC_INC_TU_FORCE:-}" ] && [ -f "$OUT" ] && [ "$OUT" -nt "$INC_ABS" ]; then
  _fresh=1
  for _peer in ${XLANG_CC_INC_TU_PEERS:-}; do
    if [ -f "$_peer" ] && [ "$_peer" -nt "$OUT" ]; then
      _fresh=0
      break
    fi
  done
  if [ "$_fresh" -eq 1 ]; then
    exit 0
  fi
fi

CC="${CC:-cc}"
BASE_CFLAGS="${CFLAGS:--Wall -Wextra -I. -Iinclude -Isrc}"
WRAP_DIR="$(dirname "$OUT")"
mkdir -p "$WRAP_DIR"
WRAP="$WRAP_DIR/.$(basename "$OUT" .o)_inc_wrap.c"

# shellcheck disable=SC2016
printf '/* generated by scripts/cc_inc_tu.sh — do not edit */\n#include "%s"\n' "$INC_ABS" >"$WRAP"
# shellcheck disable=SC2086
$CC $BASE_CFLAGS "$@" -c -o "$OUT" "$WRAP"
rm -f "$WRAP"
