#!/bin/sh
# cc_inc_tu.sh — 从 .inc 编译单一 TU（G-02e-15：薄 alias 去手写 .c）
#
# 用法（compiler/ 目录）：
#   sh scripts/cc_inc_tu.sh <rel-or-abs.inc> <out.o> [extra cc flags...]
#
# 写临时 wrap.c：#include "绝对路径.inc"，cc -c，再删除 wrap。
set -e
cd "$(dirname "$0")/.."

if [ "$#" -lt 2 ]; then
  echo "usage: cc_inc_tu.sh <file.inc> <out.o> [extra cflags...]" >&2
  exit 2
fi

INC="$1"
OUT="$2"
shift 2

case "$INC" in
  /*) INC_ABS="$INC" ;;
  *) INC_ABS="$(pwd)/$INC" ;;
esac

if [ ! -f "$INC_ABS" ]; then
  echo "cc_inc_tu: missing $INC_ABS" >&2
  exit 1
fi

CC="${CC:-cc}"
BASE_CFLAGS="${CFLAGS:--Wall -Wextra -I. -Iinclude -Isrc}"
WRAP_DIR="$(dirname "$OUT")"
mkdir -p "$WRAP_DIR"
WRAP="$WRAP_DIR/.$(basename "$OUT" .o)_inc_wrap.c"

# shellcheck disable=SC2016
printf '/* generated by scripts/cc_inc_tu.sh — do not edit */\n#include "%s"\n' "$INC_ABS" >"$WRAP"
# shellcheck disable=SC2086
$CC $BASE_CFLAGS "$@" -c -o "$OUT" "$WRAP"
rm -f "$WRAP"
