#!/usr/bin/env bash
# forbid_host_cc.sh — XLANG_FORBID_HOST_CC gate (Stage 12.2.1)
#
# When XLANG_FORBID_HOST_CC=1, replaces $CC with a wrapper that logs every
# invocation. This builds the "problem map" of all host-CC dependency points
# in the cold boot chain, guiding incremental zero-CC implementation (Stage 12).
#
# Two modes (selected at runtime by env, read inside the wrapper):
#   - BLOCK (default): log + exit 1. Build scripts with `set +e` can still
#     collect multiple violations per run, but the compile/link fails.
#   - LOG_ONLY (XLANG_FORBID_HOST_CC_LOG_ONLY=1): log + exec the real CC so
#     the build proceeds normally. Used by Stage 12.2.3 to collect the
#     EMPIRICAL problem map (which $CC calls actually fire during a real
#     L2/L4 build with PREFER_X_O=1) without blocking the build.
#
# Usage (source from any build script after CC is resolved):
#   . "$(dirname "$0")/forbid_host_cc.sh"
#
# The wrapper categorizes invocations:
#   - COMPILE: $CC invoked with -c flag (.c/.s -> .o)
#   - LINK:    $CC invoked with -o but without -c (.o -> binary)
#   - OTHER:   anything else
#
# Violations are logged to $XLANG_FORBID_HOST_CC_LOG (default:
# $BUILD_DIR/.forbid_host_cc_violations.log, fallback /tmp/xlang_forbid_host_cc.log).
#
# PLATFORM: SHARED — works on macOS/Linux/Windows(MSYS).
# When XLANG_FORBID_HOST_CC is unset or 0, this helper is a no-op (zero impact
# on normal builds).

xlang_forbid_host_cc_install() {
  [ "${XLANG_FORBID_HOST_CC:-0}" = "1" ] || return 0

  # Guard against double-install: multiple build scripts may source this
  # helper in the same shell tree (e.g. build_xlang_asm.sh then a sourced
  # g05_*.sh). If CC already points to our wrapper, the real CC was already
  # captured — re-installing would capture the wrapper as "real CC" and
  # cause infinite recursion in LOG_ONLY mode. Skip silently.
  case "${CC:-}" in
    */.forbid_host_cc_wrapper.sh|.forbid_host_cc_wrapper.sh) return 0 ;;
  esac

  local _log="${XLANG_FORBID_HOST_CC_LOG:-${BUILD_DIR:-.}/.forbid_host_cc_violations.log}"
  _log="$(mkdir -p "$(dirname "$_log")" 2>/dev/null && echo "$_log")"
  [ -n "$_log" ] || _log="/tmp/xlang_forbid_host_cc_${$}.log"
  : > "$_log" 2>/dev/null || true
  export XLANG_FORBID_HOST_CC_LOG="$_log"

  # Capture the real CC BEFORE overriding so LOG_ONLY mode can exec it.
  # CC is typically resolved by the caller before sourcing this helper
  # (cc / clang / gcc). Default to "cc" if unset.
  export XLANG_FORBID_HOST_CC_REAL_CC="${CC:-cc}"

  local _wrapper="${BUILD_DIR:-/tmp}/.forbid_host_cc_wrapper.sh"
  cat > "$_wrapper" <<'EOF_WRAPPER'
#!/usr/bin/env sh
# Auto-generated by forbid_host_cc.sh — gates host-CC when XLANG_FORBID_HOST_CC=1.
# Modes (read at runtime from env, so a single wrapper serves both):
#   XLANG_FORBID_HOST_CC_LOG_ONLY=1 → log + exec real CC (build proceeds; for
#                                    empirical problem-map collection).
#   default                         → log + exit 1 (build blocks; for gate
#                                    enforcement once a path is zero-CC).
_log="${XLANG_FORBID_HOST_CC_LOG:-/tmp/xlang_forbid_host_cc.log}"
_real_cc="${XLANG_FORBID_HOST_CC_REAL_CC:-cc}"
_log_only="${XLANG_FORBID_HOST_CC_LOG_ONLY:-0}"
_ts="$(date +%H:%M:%S.%N 2>/dev/null || date +%H:%M:%S)"
_type="OTHER"
for _a in "$@"; do
  case "$_a" in
    -c) _type="COMPILE" ;;
    -o) [ "$_type" = "OTHER" ] && _type="LINK" ;;
  esac
done
echo "[$_ts] VIOLATION [$_type]: $*" >> "$_log"
echo "  cwd=$(pwd)" >> "$_log"
if [ "$_log_only" = "1" ]; then
  echo "XLANG_FORBID_HOST_CC_LOG_ONLY: logged [$_type], exec real CC=$_real_cc" >&2
  exec "$_real_cc" "$@"
fi
echo "XLANG_FORBID_HOST_CC=1: host CC blocked [$_type]: $*" >&2
exit 1
EOF_WRAPPER
  chmod +x "$_wrapper"

  # Override CC for the current shell and all subscripts.
  CC="$_wrapper"
  export CC
  local _mode="BLOCK"
  [ "${XLANG_FORBID_HOST_CC_LOG_ONLY:-0}" = "1" ] && _mode="LOG_ONLY"
  echo "forbid_host_cc: XLANG_FORBID_HOST_CC=1 active (mode=${_mode}); CC wrapper=$_wrapper; log=$_log; real_cc=${XLANG_FORBID_HOST_CC_REAL_CC}" >&2
}

# Auto-install when sourced (if flag set; no-op otherwise).
xlang_forbid_host_cc_install
