#!/usr/bin/env bash
# forbid_host_cc.sh — XLANG_FORBID_HOST_CC gate (Stage 12.2.1)
#
# When XLANG_FORBID_HOST_CC=1, replaces $CC with a wrapper that logs every
# invocation and exits 1. This builds the "problem map" of all host-CC
# dependency points in the cold boot chain, guiding incremental zero-CC
# implementation (Stage 12).
#
# Usage (source from any build script after CC is resolved):
#   . "$(dirname "$0")/forbid_host_cc.sh"
#
# The wrapper categorizes invocations:
#   - COMPILE: $CC invoked with -c flag (.c/.s -> .o)
#   - LINK:    $CC invoked with -o but without -c (.o -> binary)
#   - OTHER:   anything else
#
# Violations are logged to $XLANG_FORBID_HOST_CC_LOG (default:
# $BUILD_DIR/.forbid_host_cc_violations.log, fallback /tmp/xlang_forbid_host_cc.log).
#
# PLATFORM: SHARED — works on macOS/Linux/Windows(MSYS).
# When XLANG_FORBID_HOST_CC is unset or 0, this helper is a no-op (zero impact
# on normal builds).

xlang_forbid_host_cc_install() {
  [ "${XLANG_FORBID_HOST_CC:-0}" = "1" ] || return 0

  local _log="${XLANG_FORBID_HOST_CC_LOG:-${BUILD_DIR:-.}/.forbid_host_cc_violations.log}"
  _log="$(mkdir -p "$(dirname "$_log")" 2>/dev/null && echo "$_log")"
  [ -n "$_log" ] || _log="/tmp/xlang_forbid_host_cc_${$}.log"
  : > "$_log" 2>/dev/null || true
  export XLANG_FORBID_HOST_CC_LOG="$_log"

  local _wrapper="${BUILD_DIR:-/tmp}/.forbid_host_cc_wrapper.sh"
  cat > "$_wrapper" <<'EOF_WRAPPER'
#!/usr/bin/env sh
# Auto-generated by forbid_host_cc.sh — blocks host-CC when XLANG_FORBID_HOST_CC=1.
# Logs the invocation and exits 1 so build scripts with `set +e` can collect
# multiple violations per run while giving clear error messages.
_log="${XLANG_FORBID_HOST_CC_LOG:-/tmp/xlang_forbid_host_cc.log}"
_ts="$(date +%H:%M:%S.%N 2>/dev/null || date +%H:%M:%S)"
_type="OTHER"
for _a in "$@"; do
  case "$_a" in
    -c) _type="COMPILE" ;;
    -o) [ "$_type" = "OTHER" ] && _type="LINK" ;;
  esac
done
echo "[$_ts] VIOLATION [$_type]: $*" >> "$_log"
echo "  cwd=$(pwd)" >> "$_log"
echo "XLANG_FORBID_HOST_CC=1: host CC blocked [$_type]: $*" >&2
exit 1
EOF_WRAPPER
  chmod +x "$_wrapper"

  # Override CC for the current shell and all subscripts.
  CC="$_wrapper"
  export CC
  echo "forbid_host_cc: XLANG_FORBID_HOST_CC=1 active; CC wrapper=$_wrapper; log=$_log" >&2
}

# Auto-install when sourced (if flag set; no-op otherwise).
xlang_forbid_host_cc_install
