#!/usr/bin/env sh
# gen_g06_phase1_backend_stub.sh — G-06 冷启动：无 seed partial 时为 phase1 生成弱符号桩 .o
#
# bootstrap_shuxc 无法对当前 asm.x 做 -E；已入库 partial 缺失时，用本脚本从链接错误收集
# backend/arch/peephole 未定义符号，生成 weak 桩，使 shux-seed-phase1 可链出并用 *_x.o 前端 -E asm.x。
#
# 用法（compiler 目录）：
#   ./scripts/gen_g06_phase1_backend_stub.sh
#
# 产出：build_asm/seed_host/asm_backend_partial.o（phase1 用；build_seed_asm_host 成功后会被真 partial 覆盖）

set -e
cd "$(dirname "$0")/.."

OUT_DIR=build_asm/seed_host
PARTIAL="$OUT_DIR/asm_backend_partial.o"
STUB_C="$OUT_DIR/asm_backend_phase1_stub_gen.c"
LINK_ERR="$OUT_DIR/phase1_link.err"
UNDEF="$OUT_DIR/phase1_undef.txt"

CC="${CC:-cc}"
CFLAGS="-Wall -Wextra -I. -Iinclude -Isrc -Wno-unused-variable -Wno-unused-parameter -Wno-unused-function -Wno-sign-compare"

os="$(uname -s | tr '[:upper:]' '[:lower:]')"
arch="$(uname -m 2>/dev/null | tr '[:upper:]' '[:lower:]')"
case "$arch" in x86_64|amd64) arch="x86_64" ;; aarch64|arm64) arch="arm64" ;; esac
case "$os" in darwin) os="darwin" ;; linux) os="linux" ;; esac
SEED="seeds/asm_backend_partial.${os}.${arch}.o"

has_real_partial_seed_mega() {
  _obj="$1"
  nm "$_obj" 2>/dev/null | awk '/ T / {
    s=$3; sub(/^_/, "", s)
    if (s == "backend_asm_codegen_ast_seed_mega") found=1
  } END { exit !found }'
}

# 已有真 partial：不生成桩
if [ -s "$PARTIAL" ] && nm "$PARTIAL" 2>/dev/null | awk '/ T / { s=$3; sub(/^_/, "", s); if (s=="backend_asm_codegen_ast_seed_mega") found=1 } END { exit !found }'; then
  echo "gen_g06_phase1_backend_stub: reuse existing $PARTIAL (strong seed_mega)" >&2
  exit 0
fi
if [ -f "$SEED" ] && [ -s "$SEED" ] && has_real_partial_seed_mega "$SEED"; then
  mkdir -p "$OUT_DIR"
  cat "$SEED" > "$PARTIAL"
  echo "gen_g06_phase1_backend_stub: seed partial <- $SEED" >&2
  exit 0
fi
if [ -f "$SEED" ] && [ -s "$SEED" ]; then
  echo "gen_g06_phase1_backend_stub: ignore non-real seed $SEED (missing strong seed_mega)" >&2
fi

mkdir -p "$OUT_DIR"

# phase1 试链需要 DRIVER_SEED_OBJS 中的 io 桩；gen 脚本可能在 recipe 中段先于最终 prerequisite 链执行。
if [ ! -f src/x_seed_bridge.o ]; then
  make src/x_seed_bridge.o >/dev/null 2>&1 || {
    echo "gen_g06_phase1_backend_stub: failed to build src/x_seed_bridge.o" >&2
    exit 1
  }
fi

# 从 make -n 取 phase1 链接命令（去掉 partial 参数）
LINK_LINE=$(make -n bootstrap-driver-seed 2>/dev/null | grep ' -o shux-seed-phase1 ' | head -1)
if [ -z "$LINK_LINE" ]; then
  echo "gen_g06_phase1_backend_stub: cannot get phase1 link line from make -n" >&2
  exit 1
fi
LINK_NO_PARTIAL=$(printf '%s\n' "$LINK_LINE" | sed 's/ build_asm\/seed_host\/asm_backend_partial.o//')

objs=$(printf '%s\n' "$LINK_NO_PARTIAL" | tr ' ' '\n' | grep -E '\.o$' || true)
for obj in $objs; do
  if [ ! -f "$obj" ]; then
    make "$obj" >/dev/null 2>&1 || true
  fi
done

# 试链，收集 undefined reference
rm -f "$LINK_ERR" "$UNDEF"
eval "$LINK_NO_PARTIAL" 2>"$LINK_ERR" || true
grep 'undefined reference to' "$LINK_ERR" 2>/dev/null \
  | sed "s/.*undefined reference to \`//; s/'.*//" \
  | sort -u >"$UNDEF" || true

if [ ! -s "$UNDEF" ]; then
  echo "gen_g06_phase1_backend_stub: no undefined symbols (unexpected); see $LINK_ERR" >&2
  tail -20 "$LINK_ERR" >&2
  exit 1
fi

echo "gen_g06_phase1_backend_stub: $(wc -l <"$UNDEF" | tr -d ' ') undefined syms -> $STUB_C" >&2

# 生成 C：void 返回 0；非 void 指针返回 NULL；其余 int32_t 返回 -1
{
  echo "/* AUTO-GENERATED by gen_g06_phase1_backend_stub.sh — G-06 phase1 only; replaced after build_seed_asm_host */"
  echo "#include <stdint.h>"
  echo "#include <stddef.h>"
  while read -r sym; do
    [ -z "$sym" ] && continue
    case "$sym" in
      fs_posix_read_c|fs_posix_write_c|fs_posix_stat_c)
        echo "__attribute__((weak)) int32_t ${sym}(void *a, void *b, void *c, void *d) { (void)a;(void)b;(void)c;(void)d; return -1; }"
        ;;
      *_init|*_prime*|expr_layout_prime*)
        echo "__attribute__((weak)) void ${sym}(void) {}"
        ;;
      *emit*|*globl*|*label*|*prologue*|*epilogue*|*call*|*jmp*|*jz*|*jnz*|*jeq*|*ret*)
        echo "__attribute__((weak)) void ${sym}(void *a, void *b, void *c, void *d, void *e) { (void)a;(void)b;(void)c;(void)d;(void)e; }"
        ;;
      *)
        echo "__attribute__((weak)) int32_t ${sym}(void *a, void *b, void *c, void *d) { (void)a;(void)b;(void)c;(void)d; return -1; }"
        ;;
    esac
  done <"$UNDEF"
} >"$STUB_C"

$CC $CFLAGS -c "$STUB_C" -o "$PARTIAL"
echo "gen_g06_phase1_backend_stub: OK $PARTIAL ($(wc -c <"$PARTIAL" | tr -d ' ') bytes)" >&2
