#!/usr/bin/env perl
# gen_asm_full_link_stubs.pl — 为 asm_full.o + dispatch .o 内 U 的 arch_enc/emit 生成 weak 桩
# 用法：gen_asm_full_link_stubs.pl <out.c> <obj1> [obj2 ...]
# PLATFORM: SHARED — emits __attribute__((weak)) stubs on ELF (Linux/macOS)
#            so real implementations (arch_*.o, backend.o) override them at
#            link time. On PE/MinGW (Windows), weak symbols do NOT satisfy
#            undefined references the same way (PE weak externs use a
#            different mechanism via .weak alias + default, and GNU ld on
#            MinGW leaves undefined refs unsatisfied even when a weak def
#            is present). For MinGW we emit NORMAL (non-weak) definitions;
#            duplicate-definition conflicts with real impls are resolved
#            by -Wl,--allow-multiple-definition (WIN_LDFLAGS in Makefile).
#            See project memory: "Windows/MinGW: __attribute__((weak))
#            函数符号不被 PE 格式支持".
use strict;
use warnings;
my $out = shift @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";
my @objs = @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";

# Detect MinGW/MSYS/Cygwin perl host. $^O reports:
#   linux   -> Linux
#   darwin  -> macOS
#   msys    -> MSYS Git Bash perl
#   cygwin  -> Cygwin perl
#   MSWin32 -> Strawberry/ActiveState perl on Windows
# On any Windows-flavored perl, emit non-weak stubs for PE link compatibility.
my $is_windows = ($^O eq 'MSWin32' || $^O eq 'msys' || $^O eq 'cygwin');
my $weak_attr = $is_windows ? '' : '__attribute__((weak)) ';

my %want;
for my $obj (@objs) {
  open my $nm, '-|', 'nm', $obj or die "nm $obj: $!\n";
  while (<$nm>) {
    next unless /\sU\s(\S+)/;
    my $sym = $1;
    $sym =~ s/^_//;
    next unless $sym =~ /^(?:arch_(?:arm64|x86_64|riscv64)_.+|
                          platform_(?:macho|coff)_.+|
                          peephole_.+|
                          backend_fold_.+|
                          fold_.+|
                          emit_bytes(?:_from_ptr|_\d+)|
                          emit_indent|
                          elf_section_code_len|
                          append_byte|
                          format_int|
                          arch_emit_.+|
                          enc_[A-Za-z0-9_]+)$/x;
    $want{$sym} = 1;
  }
  close $nm;
}
# PLATFORM: SHARED — Write to a temp file then atomically replace the existing
# $out only if the generated content changed. Why: the Makefile rule depends on
# .o inputs (pipeline_x.o, ASM_GLUE_STANDALONE_O, USER_ASM_SEED_OBJS). Within a
# single `make` run, if user_asm_seed_bridge.o is rebuilt AFTER stubs.o (because
# stubs.o also depends on pipeline_x.o which was rebuilt first), the new U
# symbols introduced by the fresh user_asm_seed_bridge.o are NOT in stubs.c,
# and the final link fails with "undefined reference" on PE/MinGW (weak stubs
# would mask this on ELF, but PE has no weak function symbols). Writing in
# place would also bump stubs.c mtime even when content is identical, forcing
# needless stubs.o recompiles on every make. By generating to a temp file and
# replacing only on content change, we (a) keep stubs.c mtime stable when the
# symbol set is unchanged (no spurious rebuilds), and (b) always emit the
# correct current symbol set when the rule does fire. The Makefile rule still
# `rm -f stubs.c stubs.o` in bootstrap-driver-seed before re-running this
# script, so a clean bootstrap always regenerates from scratch.
my $tmp = $out . ".tmp.$$";
open my $fh, '>', $tmp or die "write $tmp: $!\n";
print $fh "/* AUTO-GENERATED by gen_asm_full_link_stubs.pl — asm.x -E / dispatch link stubs\n";
print $fh " * PLATFORM: " . ($is_windows ? "WINDOWS | MSYS | MINGW (non-weak stubs; PE weak alias does not satisfy U refs)" : "POSIX (weak stubs; real impls override)") . " */\n";
print $fh "#include <stdint.h>\n\n";
for my $sym (sort keys %want) {
  print $fh "${weak_attr}int32_t ${sym}(void *a, void *b, void *c, void *d) {\n";
  print $fh "  (void)a; (void)b; (void)c; (void)d;\n";
  print $fh "  return -1;\n";
  print $fh "}\n\n";
}
close $fh;
my $kind = $is_windows ? "normal" : "weak";
my $n_stubs = scalar(keys %want);
# Compare with existing $out; replace only on content difference.
my $replace = 1;
if (-f $out) {
  eval {
    open my $old, '<', $out or die "open $out: $!\n";
    local $/;
    my $old_content = <$old>;
    close $old;
    open my $new, '<', $tmp or die "open $tmp: $!\n";
    my $new_content = <$new>;
    close $new;
    $replace = ($old_content ne $new_content) ? 1 : 0;
  };
}
if ($replace) {
  rename $tmp, $out or die "rename $tmp -> $out: $!\n";
  print STDERR "gen_asm_full_link_stubs: $n_stubs $kind stubs -> $out (updated)\n";
} else {
  unlink $tmp or die "unlink $tmp: $!\n";
  print STDERR "gen_asm_full_link_stubs: $n_stubs $kind stubs -> $out (unchanged, kept)\n";
}
