#!/usr/bin/env perl
# gen_asm_full_link_stubs.pl — 为 asm_full.o + dispatch .o 内 U 的 arch_enc/emit 生成 weak 桩
# 用法：gen_asm_full_link_stubs.pl <out.c> <obj1> [obj2 ...]
use strict;
use warnings;
my $out = shift @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";
my @objs = @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";
my %want;
for my $obj (@objs) {
  open my $nm, '-|', 'nm', $obj or die "nm $obj: $!\n";
  while (<$nm>) {
    next unless /\sU\s(\S+)/;
    my $sym = $1;
    $sym =~ s/^_//;
    next unless $sym =~ /^arch_(?:arm64|x86_64|riscv64)_(?:enc_enc_|emit_)/;
    $want{$sym} = 1;
  }
  close $nm;
}
open my $fh, '>', $out or die "write $out: $!\n";
print $fh "/* AUTO-GENERATED by gen_asm_full_link_stubs.pl — asm.sx -E / dispatch link stubs */\n";
print $fh "#include <stdint.h>\n\n";
for my $sym (sort keys %want) {
  print $fh "__attribute__((weak)) int32_t ${sym}(void *a, void *b, void *c, void *d) {\n";
  print $fh "  (void)a; (void)b; (void)c; (void)d;\n";
  print $fh "  return -1;\n";
  print $fh "}\n\n";
}
close $fh;
print STDERR "gen_asm_full_link_stubs: ", scalar(keys %want), " weak stubs -> $out\n";
