#!/usr/bin/env perl
# gen_asm_full_link_stubs.pl — 为 asm_full.o + dispatch .o 内 U 的 arch_enc/emit 生成 weak 桩
# 用法：gen_asm_full_link_stubs.pl <out.c> <obj1> [obj2 ...]
# PLATFORM: SHARED — emits __attribute__((weak)) stubs on ELF (Linux/macOS)
#            so real implementations (arch_*.o, backend.o) override them at
#            link time. On PE/MinGW (Windows), weak symbols do NOT satisfy
#            undefined references the same way (PE weak externs use a
#            different mechanism via .weak alias + default, and GNU ld on
#            MinGW leaves undefined refs unsatisfied even when a weak def
#            is present). For MinGW we emit NORMAL (non-weak) definitions;
#            duplicate-definition conflicts with real impls are resolved
#            by -Wl,--allow-multiple-definition (WIN_LDFLAGS in Makefile).
#            See project memory: "Windows/MinGW: __attribute__((weak))
#            函数符号不被 PE 格式支持".
use strict;
use warnings;
my $out = shift @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";
my @objs = @ARGV or die "usage: gen_asm_full_link_stubs.pl <out.c> <obj...>\n";

# Detect MinGW/MSYS/Cygwin perl host. $^O reports:
#   linux   -> Linux
#   darwin  -> macOS
#   msys    -> MSYS Git Bash perl
#   cygwin  -> Cygwin perl
#   MSWin32 -> Strawberry/ActiveState perl on Windows
# On any Windows-flavored perl, emit non-weak stubs for PE link compatibility.
my $is_windows = ($^O eq 'MSWin32' || $^O eq 'msys' || $^O eq 'cygwin');
my $weak_attr = $is_windows ? '' : '__attribute__((weak)) ';

my %want;
for my $obj (@objs) {
  open my $nm, '-|', 'nm', $obj or die "nm $obj: $!\n";
  while (<$nm>) {
    next unless /\sU\s(\S+)/;
    my $sym = $1;
    $sym =~ s/^_//;
    next unless $sym =~ /^(?:arch_(?:arm64|x86_64|riscv64)_.+|
                          platform_(?:macho|coff)_.+|
                          peephole_.+|
                          backend_fold_.+|
                          fold_.+|
                          emit_bytes(?:_from_ptr|_\d+)|
                          emit_indent|
                          elf_section_code_len|
                          append_byte|
                          format_int|
                          arch_emit_.+|
                          enc_[A-Za-z0-9_]+)$/x;
    $want{$sym} = 1;
  }
  close $nm;
}
open my $fh, '>', $out or die "write $out: $!\n";
print $fh "/* AUTO-GENERATED by gen_asm_full_link_stubs.pl — asm.x -E / dispatch link stubs\n";
print $fh " * PLATFORM: " . ($is_windows ? "WINDOWS | MSYS | MINGW (non-weak stubs; PE weak alias does not satisfy U refs)" : "POSIX (weak stubs; real impls override)") . " */\n";
print $fh "#include <stdint.h>\n\n";
for my $sym (sort keys %want) {
  print $fh "${weak_attr}int32_t ${sym}(void *a, void *b, void *c, void *d) {\n";
  print $fh "  (void)a; (void)b; (void)c; (void)d;\n";
  print $fh "  return -1;\n";
  print $fh "}\n\n";
}
close $fh;
my $kind = $is_windows ? "normal" : "weak";
print STDERR "gen_asm_full_link_stubs: ", scalar(keys %want), " $kind stubs -> $out\n";
