#include <stdint.h>
#include <stddef.h>
#include <sys/types.h>
void shux_panic_(int has_msg, int msg_val);
struct lexer_Lexer {
  size_t pos;
  int32_t line;
  int32_t col;
};

struct lexer_LexerResult {
  struct lexer_Lexer next_lex;
  struct token_Token tok;
  size_t token_start;
};

enum token_TokenKind { token_TokenKind_TOKEN_EOF, token_TokenKind_TOKEN_FUNCTION, token_TokenKind_TOKEN_LET, token_TokenKind_TOKEN_CONST, token_TokenKind_TOKEN_IF, token_TokenKind_TOKEN_ELSE, token_TokenKind_TOKEN_WHILE, token_TokenKind_TOKEN_LOOP, token_TokenKind_TOKEN_FOR, token_TokenKind_TOKEN_BREAK, token_TokenKind_TOKEN_CONTINUE, token_TokenKind_TOKEN_RETURN, token_TokenKind_TOKEN_PANIC, token_TokenKind_TOKEN_DEFER, token_TokenKind_TOKEN_TRY, token_TokenKind_TOKEN_CATCH, token_TokenKind_TOKEN_REGION, token_TokenKind_TOKEN_WITH_ARENA, token_TokenKind_TOKEN_MATCH, token_TokenKind_TOKEN_STRUCT, token_TokenKind_TOKEN_TYPE, token_TokenKind_TOKEN_PACKED, token_TokenKind_TOKEN_SOA, token_TokenKind_TOKEN_ATTR_SOA, token_TokenKind_TOKEN_ATTR_CFG, token_TokenKind_TOKEN_ATTR_REPR_C, token_TokenKind_TOKEN_ATTR_REPR_COMPATIBLE, token_TokenKind_TOKEN_ATTR_ALLOC, token_TokenKind_TOKEN_ATTR_LINK_SECTION, token_TokenKind_TOKEN_ATTR_NAKED, token_TokenKind_TOKEN_ATTR_ENTRY, token_TokenKind_TOKEN_ATTR_USED, token_TokenKind_TOKEN_ATTR_NO_MANGLE, token_TokenKind_TOKEN_ATTR_LINK_NAME, token_TokenKind_TOKEN_ATTR_MAX_STACK, token_TokenKind_TOKEN_ATTR_INTERRUPT, token_TokenKind_TOKEN_ATTR_SEND, token_TokenKind_TOKEN_ATTR_SYNC, token_TokenKind_TOKEN_ATTR_GLOBAL_ALLOCATOR, token_TokenKind_TOKEN_ATTR_COLD, token_TokenKind_TOKEN_ATTR_INLINE_NEVER, token_TokenKind_TOKEN_ATTR_INLINE_ALWAYS, token_TokenKind_TOKEN_ATTR_EXPORT_NAME, token_TokenKind_TOKEN_ATTR_PANIC_HANDLER, token_TokenKind_TOKEN_ATTR_THREAD_LOCAL, token_TokenKind_TOKEN_ATTR_PERCPU, token_TokenKind_TOKEN_ALIGN, token_TokenKind_TOKEN_ENUM, token_TokenKind_TOKEN_GOTO, token_TokenKind_TOKEN_TRAIT, token_TokenKind_TOKEN_IMPL, token_TokenKind_TOKEN_SELF, token_TokenKind_TOKEN_UNDERSCORE, token_TokenKind_TOKEN_IMPORT, token_TokenKind_TOKEN_EXTERN, token_TokenKind_TOKEN_ASYNC, token_TokenKind_TOKEN_AWAIT, token_TokenKind_TOKEN_RUN, token_TokenKind_TOKEN_SPAWN, token_TokenKind_TOKEN_IDENT, token_TokenKind_TOKEN_I32, token_TokenKind_TOKEN_BOOL, token_TokenKind_TOKEN_U8, token_TokenKind_TOKEN_U32, token_TokenKind_TOKEN_U64, token_TokenKind_TOKEN_I64, token_TokenKind_TOKEN_USIZE, token_TokenKind_TOKEN_ISIZE, token_TokenKind_TOKEN_I32X4, token_TokenKind_TOKEN_I32X8, token_TokenKind_TOKEN_I32X16, token_TokenKind_TOKEN_U32X4, token_TokenKind_TOKEN_U32X8, token_TokenKind_TOKEN_U32X16, token_TokenKind_TOKEN_F32X4, token_TokenKind_TOKEN_TRUE, token_TokenKind_TOKEN_FALSE, token_TokenKind_TOKEN_F32, token_TokenKind_TOKEN_F64, token_TokenKind_TOKEN_VOID, token_TokenKind_TOKEN_INT, token_TokenKind_TOKEN_FLOAT, token_TokenKind_TOKEN_LPAREN, token_TokenKind_TOKEN_RPAREN, token_TokenKind_TOKEN_LBRACE, token_TokenKind_TOKEN_RBRACE, token_TokenKind_TOKEN_LBRACKET, token_TokenKind_TOKEN_RBRACKET, token_TokenKind_TOKEN_ARROW, token_TokenKind_TOKEN_FATARROW, token_TokenKind_TOKEN_COMMA, token_TokenKind_TOKEN_COLON, token_TokenKind_TOKEN_DOT, token_TokenKind_TOKEN_DOTDOT, token_TokenKind_TOKEN_ELLIPSIS, token_TokenKind_TOKEN_SEMICOLON, token_TokenKind_TOKEN_PLUS, token_TokenKind_TOKEN_MINUS, token_TokenKind_TOKEN_STAR, token_TokenKind_TOKEN_SLASH, token_TokenKind_TOKEN_PERCENT, token_TokenKind_TOKEN_AMP, token_TokenKind_TOKEN_PIPE, token_TokenKind_TOKEN_CARET, token_TokenKind_TOKEN_LSHIFT, token_TokenKind_TOKEN_RSHIFT, token_TokenKind_TOKEN_PLUS_EQ, token_TokenKind_TOKEN_MINUS_EQ, token_TokenKind_TOKEN_STAR_EQ, token_TokenKind_TOKEN_SLASH_EQ, token_TokenKind_TOKEN_PERCENT_EQ, token_TokenKind_TOKEN_AMP_EQ, token_TokenKind_TOKEN_PIPE_EQ, token_TokenKind_TOKEN_CARET_EQ, token_TokenKind_TOKEN_LSHIFT_EQ, token_TokenKind_TOKEN_RSHIFT_EQ, token_TokenKind_TOKEN_TILDE, token_TokenKind_TOKEN_ASSIGN, token_TokenKind_TOKEN_EQ, token_TokenKind_TOKEN_NE, token_TokenKind_TOKEN_LT, token_TokenKind_TOKEN_GT, token_TokenKind_TOKEN_LE, token_TokenKind_TOKEN_GE, token_TokenKind_TOKEN_AMPAMP, token_TokenKind_TOKEN_PIPEPIPE, token_TokenKind_TOKEN_BANG, token_TokenKind_TOKEN_QUESTION, token_TokenKind_TOKEN_AS, token_TokenKind_TOKEN_AT, token_TokenKind_TOKEN_STRING, token_TokenKind_TOKEN_EXPORT };
struct token_Token {
  int32_t kind;
  int32_t line;
  int32_t col;
  int64_t int_val;
  double float_val;
  uint8_t * ident;
  int32_t ident_len;
};

enum ast_TypeKind { ast_TypeKind_TYPE_I32, ast_TypeKind_TYPE_BOOL, ast_TypeKind_TYPE_U8, ast_TypeKind_TYPE_U32, ast_TypeKind_TYPE_U64, ast_TypeKind_TYPE_I64, ast_TypeKind_TYPE_USIZE, ast_TypeKind_TYPE_ISIZE, ast_TypeKind_TYPE_NAMED, ast_TypeKind_TYPE_PTR, ast_TypeKind_TYPE_ARRAY, ast_TypeKind_TYPE_SLICE, ast_TypeKind_TYPE_LINEAR, ast_TypeKind_TYPE_VECTOR, ast_TypeKind_TYPE_F32, ast_TypeKind_TYPE_F64, ast_TypeKind_TYPE_VOID };
enum ast_ExprKind { ast_ExprKind_EXPR_LIT, ast_ExprKind_EXPR_FLOAT_LIT, ast_ExprKind_EXPR_BOOL_LIT, ast_ExprKind_EXPR_VAR, ast_ExprKind_EXPR_ADD, ast_ExprKind_EXPR_SUB, ast_ExprKind_EXPR_MUL, ast_ExprKind_EXPR_DIV, ast_ExprKind_EXPR_MOD, ast_ExprKind_EXPR_SHL, ast_ExprKind_EXPR_SHR, ast_ExprKind_EXPR_BITAND, ast_ExprKind_EXPR_BITOR, ast_ExprKind_EXPR_BITXOR, ast_ExprKind_EXPR_EQ, ast_ExprKind_EXPR_NE, ast_ExprKind_EXPR_LT, ast_ExprKind_EXPR_LE, ast_ExprKind_EXPR_GT, ast_ExprKind_EXPR_GE, ast_ExprKind_EXPR_LOGAND, ast_ExprKind_EXPR_LOGOR, ast_ExprKind_EXPR_NEG, ast_ExprKind_EXPR_BITNOT, ast_ExprKind_EXPR_LOGNOT, ast_ExprKind_EXPR_IF, ast_ExprKind_EXPR_BLOCK, ast_ExprKind_EXPR_TERNARY, ast_ExprKind_EXPR_ASSIGN, ast_ExprKind_EXPR_ADD_ASSIGN, ast_ExprKind_EXPR_SUB_ASSIGN, ast_ExprKind_EXPR_MUL_ASSIGN, ast_ExprKind_EXPR_DIV_ASSIGN, ast_ExprKind_EXPR_MOD_ASSIGN, ast_ExprKind_EXPR_BITAND_ASSIGN, ast_ExprKind_EXPR_BITOR_ASSIGN, ast_ExprKind_EXPR_BITXOR_ASSIGN, ast_ExprKind_EXPR_SHL_ASSIGN, ast_ExprKind_EXPR_SHR_ASSIGN, ast_ExprKind_EXPR_BREAK, ast_ExprKind_EXPR_CONTINUE, ast_ExprKind_EXPR_RETURN, ast_ExprKind_EXPR_PANIC, ast_ExprKind_EXPR_MATCH, ast_ExprKind_EXPR_FIELD_ACCESS, ast_ExprKind_EXPR_STRUCT_LIT, ast_ExprKind_EXPR_ARRAY_LIT, ast_ExprKind_EXPR_INDEX, ast_ExprKind_EXPR_CALL, ast_ExprKind_EXPR_METHOD_CALL, ast_ExprKind_EXPR_ENUM_VARIANT, ast_ExprKind_EXPR_ADDR_OF, ast_ExprKind_EXPR_DEREF, ast_ExprKind_EXPR_BINOP, ast_ExprKind_EXPR_AS, ast_ExprKind_EXPR_AWAIT, ast_ExprKind_EXPR_RUN, ast_ExprKind_EXPR_SPAWN, ast_ExprKind_EXPR_TRY_PROPAGATE, ast_ExprKind_EXPR_STRING_LIT };
enum ast_ImportKind { ast_ImportKind_IMPORT_WHOLE, ast_ImportKind_IMPORT_BINDING, ast_ImportKind_IMPORT_SELECT };
struct ast_Type {
  int32_t kind;
  uint8_t name[64];
  int32_t name_len;
  int32_t elem_type_ref;
  int32_t array_size;
  uint8_t region_label[64];
  int32_t region_label_len;
};

struct ast_Expr {
  int32_t kind;
  int32_t resolved_type_ref;
  int32_t line;
  int32_t col;
  int64_t int_val;
  double float_val;
  uint8_t var_name[64];
  int32_t var_name_len;
  int32_t binop_left_ref;
  int32_t binop_right_ref;
  int32_t unary_operand_ref;
  int32_t if_cond_ref;
  int32_t if_then_ref;
  int32_t if_else_ref;
  int32_t block_ref;
  int32_t match_matched_ref;
  int32_t match_arm_base;
  int32_t match_num_arms;
  int32_t field_access_base_ref;
  uint8_t field_access_field_name[64];
  int32_t field_access_field_len;
  int32_t field_access_is_enum_variant;
  int32_t field_access_offset;
  int32_t field_access_soa_stride;
  int32_t index_base_ref;
  int32_t index_index_ref;
  int32_t index_base_is_slice;
  int32_t call_callee_ref;
  int32_t call_arg_base;
  int32_t call_num_args;
  int32_t call_num_type_args;
  int32_t method_call_base_ref;
  uint8_t method_call_name[64];
  int32_t method_call_name_len;
  int32_t method_call_arg_base;
  int32_t method_call_num_args;
  int32_t const_folded_val;
  int32_t const_folded_valid;
  int32_t index_proven_in_bounds;
  uint8_t struct_lit_struct_name[64];
  int32_t struct_lit_struct_name_len;
  int32_t struct_lit_field_base;
  int32_t struct_lit_num_fields;
  int32_t array_lit_elem_base;
  int32_t array_lit_num_elems;
  int32_t float_bits_lo;
  int32_t float_bits_hi;
  int32_t enum_variant_tag;
  int32_t as_operand_ref;
  int32_t as_target_type_ref;
  int32_t call_resolved_func_index;
  int32_t call_resolved_dep_index;
};

struct ast_ConstDecl {
  uint8_t name[64];
  int32_t name_len;
  int32_t type_ref;
  int32_t init_ref;
};

struct ast_LetDecl {
  uint8_t name[64];
  int32_t name_len;
  int32_t type_ref;
  int32_t init_ref;
};

struct ast_WhileLoop {
  int32_t cond_ref;
  int32_t body_ref;
};

struct ast_ForLoop {
  int32_t init_ref;
  int32_t cond_ref;
  int32_t step_ref;
  int32_t body_ref;
};

struct ast_IfStmt {
  int32_t cond_ref;
  int32_t then_body_ref;
  int32_t else_body_ref;
};

struct ast_StmtOrderItem {
  uint8_t kind;
  int32_t idx;
};

struct ast_LabeledStmt {
  uint8_t label[32];
  int32_t label_len;
  int32_t is_goto;
  uint8_t goto_target[32];
  int32_t goto_target_len;
  int32_t return_expr_ref;
};

struct ast_Block {
  int32_t const_base;
  int32_t num_consts;
  int32_t let_base;
  int32_t num_lets;
  int32_t num_early_lets;
  int32_t loop_base;
  int32_t num_loops;
  int32_t for_loop_base;
  int32_t num_for_loops;
  int32_t if_base;
  int32_t num_if_stmts;
  int32_t region_base;
  int32_t num_regions;
  int32_t defer_base;
  int32_t num_defers;
  int32_t labeled_base;
  int32_t num_labeled_stmts;
  int32_t expr_stmt_base;
  int32_t num_expr_stmts;
  int32_t final_expr_ref;
  int32_t stmt_order_base;
  int32_t num_stmt_order;
  int32_t parent_block_ref;
};

struct ast_Param {
  uint8_t name[32];
  int32_t name_len;
  int32_t type_ref;
};

struct ast_Func {
  uint8_t name[64];
  int32_t name_len;
  int32_t param_base;
  int32_t num_params;
  int32_t num_generic_params;
  int32_t return_type_ref;
  int32_t body_ref;
  int32_t body_expr_ref;
  int32_t is_extern;
  int32_t is_async;
  int32_t is_used;
  int32_t is_naked;
  int32_t is_entry;
  int32_t is_no_mangle;
  int32_t is_interrupt;
  int32_t abi_kind;
  int32_t is_variadic;
  int32_t is_export;
};

struct ast_StructLayout {
  uint8_t name[64];
  int32_t name_len;
  int32_t field_base;
  int32_t num_fields;
  int32_t allow_padding;
  int32_t soa;
  int32_t packed;
  int32_t repr_compatible;
  int32_t is_export;
};

struct ast_Module {
  int32_t num_funcs;
  int32_t main_func_index;
  int32_t num_imports;
  int32_t num_top_level_lets;
  int32_t num_struct_layouts;
  int32_t pending_allow_padding;
  int32_t pending_soa_struct;
  int32_t pending_cfg_skip;
  int32_t pending_repr_c_struct;
  int32_t pending_repr_compatible_struct;
  int32_t pending_used;
  int32_t pending_naked;
  int32_t pending_entry;
  int32_t pending_no_mangle;
  int32_t pending_interrupt;
  int32_t pending_export;
  int32_t num_module_enums;
};

struct ast_ASTArena {
  int32_t num_types;
  int32_t num_exprs;
  int32_t num_blocks;
  int32_t num_funcs;
};

struct ast_PipelineDepCtx {
  int32_t ndep;
  uint8_t entry_dir_buf[512];
  int32_t entry_dir_len;
  int32_t num_lib_roots;
  uint8_t path_buf[512];
  uint8_t loaded_buf[4194304];
  ssize_t loaded_len;
  uint8_t preprocess_buf[4194304];
  int32_t preprocess_len;
  int32_t use_asm_backend;
  int32_t target_arch;
  int32_t target_cpu_features;
  int32_t use_macho_o;
  int32_t use_coff_o;
  int32_t current_block_ref;
  int32_t typeck_loop_depth;
  int32_t current_func_index;
  int32_t skip_codegen_dep_0;
  int32_t entry_already_parsed;
  int32_t current_func_single_empty_param_index;
  int32_t current_func_empty_param_count;
  int32_t current_emit_empty_var_next_index;
  int32_t emit_expr_as_callee;
  struct ast_Module * current_codegen_module;
  struct ast_ASTArena * current_codegen_arena;
  int32_t current_codegen_dep_index;
  uint8_t current_codegen_prefix_mirror[64];
  int32_t current_codegen_prefix_len;
  int32_t asm_entry_module_only;
  uint8_t entry_module_import_path_mirror[64];
  int32_t entry_module_import_path_len;
  int32_t typeck_scope_region_len;
  uint8_t typeck_scope_region_label[64];
};

struct lexer_Lexer;
struct lexer_LexerResult;
struct token_Token;
struct ast_Type;
struct ast_Expr;
struct ast_ConstDecl;
struct ast_LetDecl;
struct ast_WhileLoop;
struct ast_ForLoop;
struct ast_IfStmt;
struct ast_StmtOrderItem;
struct ast_LabeledStmt;
struct ast_Block;
struct ast_Param;
struct ast_Func;
struct ast_StructLayout;
struct ast_Module;
struct ast_ASTArena;
struct ast_PipelineDepCtx;
extern struct lexer_Lexer lexer_init(void);
extern int32_t pipeline_arena_type_cap(void);
extern int32_t pipeline_arena_expr_cap(void);
extern int32_t pipeline_arena_block_cap(void);
extern int32_t pipeline_arena_func_cap(void);
extern int32_t ast_ast_placeholder(void);
struct OneFuncResult {
  int ok;
  struct lexer_Lexer next_lex;
  uint8_t name[64];
  int32_t name_len;
  int32_t num_params;
  int32_t num_generic_params;
  int32_t num_consts;
  int32_t num_lets;
  int has_if_expr;
  int if_cond_true;
  int32_t if_then_val;
  int32_t if_else_val;
  int32_t if_cond_expr_ref;
  int has_mul;
  int32_t mul_right_val;
  int has_binop;
  int32_t binop_right_val;
  int32_t binop_left_param_idx;
  int32_t binop_right_param_idx;
  int has_unary_neg;
  int32_t return_val;
  int has_call_expr;
  uint8_t call_callee_name[64];
  int32_t call_callee_len;
  uint8_t return_var_name[64];
  int32_t return_var_name_len;
  int32_t return_expr_ref;
  int has_final_expr;
  int has_explicit_return_kw;
  int32_t call_num_args;
  int32_t num_loops;
  int32_t num_for_loops;
  int32_t num_if_stmts;
  int32_t num_src_stmt_order;
  int32_t num_src_body_expr_stmts;
  int32_t func_return_type_ref;
};

struct ParseResult {
  int ok;
  int32_t return_val;
};

struct ParseIntoResult {
  int32_t ok;
  int32_t main_idx;
};

struct TopLevelLetResult {
  int ok;
  struct lexer_Lexer next_lex;
};

struct TypeAliasResult {
  int ok;
  struct lexer_Lexer next_lex;
};

struct CollectImportsResult {
  struct lexer_Lexer lex;
};

struct ParseExprResult {
  int ok;
  int32_t expr_ref;
  struct lexer_Lexer next_lex;
};

struct ParseBlockResult {
  int ok;
  int32_t block_ref;
  struct lexer_Lexer next_lex;
};

struct ExternParseResult {
  struct lexer_Lexer next_lex;
  uint8_t name[64];
  int32_t name_len;
  int32_t return_ty_ref;
  int32_t num_params;
  int32_t abi_kind;
  int32_t is_variadic;
};

struct TrySkipAllowResult {
  struct lexer_Lexer lex;
  int32_t skipped;
  uint8_t _pad[4];
};

struct LibraryParseResult {
  int ok;
  uint8_t _pad[4];
  struct lexer_Lexer next_lex;
  uint8_t name[64];
  int32_t name_len;
  uint8_t _pad_tail[4];
};

struct LibraryParseScanResult {
  int ok;
  uint8_t _pad[4];
  struct lexer_Lexer next_lex;
  uint8_t name[64];
  int32_t name_len;
  uint8_t param_name[32];
  int32_t param_name_len;
  uint8_t param_type_name[64];
  int32_t param_type_len;
  uint8_t field_name[64];
  int32_t field_len;
  uint8_t _pad_tail[4];
  uint8_t _pad_tail2[4];
};

extern struct OneFuncResult onefunc_scratch_empty(void);
static struct lexer_Lexer rewound;
static int32_t rl;
static size_t start;
static int32_t ko;
static struct lexer_Lexer lex_out;
static struct lexer_Lexer lp_base;
static int32_t back_lp;
static struct lexer_Lexer lex_lp;
static struct lexer_LexerResult r_lp;
static size_t p;
static size_t p;
static uint8_t sep;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static uint8_t z64[64];
static struct OneFuncResult _prime;
static struct lexer_LexerResult r_tail;
static struct lexer_Lexer lex_tail;
static struct OneFuncResult _q2;
static struct OneFuncResult _q3;
static uint8_t ccn[64];
static struct OneFuncResult _q4;
static uint8_t rvn[64];
static struct OneFuncResult _q4b;
static struct OneFuncResult _q5;
static struct OneFuncResult _q6;
static int32_t preserved_func_ret_ty;
static int32_t ni;
static int32_t rvni;
static int32_t cci;
static int32_t ni;
static struct OneFuncResult _w;
static struct OneFuncResult _w;
static struct OneFuncResult _w;
static struct OneFuncResult _w;
static struct OneFuncResult _w;
static struct OneFuncResult _w;
static uint8_t dummy_name[64];
static struct OneFuncResult res;
static int32_t rvni;
static int32_t _so;
static int32_t ref;
static struct ast_Expr e;
static int32_t ref;
static struct ast_Expr e;
static struct ast_Expr inner;
static int32_t wrap;
static struct ast_Expr rwe;
static struct ast_Type rtw;
static struct shux_slice_uint8_t slice;
static size_t scratch_sz;
static uint8_t * scratch_raw;
static struct OneFuncResult * temp;
static struct lexer_Lexer lex_cur;
static int32_t block_ref;
static struct ast_Block b;
static int32_t block_prefix_lets;
static int32_t ci;
static int32_t li;
static struct lexer_LexerResult r_peek_blk;
static struct lexer_LexerResult r;
static int stmt_tok_ready;
static int32_t pb_break;
static int32_t let_base_mid;
static int32_t kw_back_mid;
static struct lexer_Lexer lex_mid_let;
static int32_t pi_mid;
static int32_t label_len_blk;
static size_t label_start_blk;
static struct lexer_LexerResult colon_blk;
static int32_t goto_len_blk;
static size_t goto_start_blk;
static uint8_t goto_row_blk[32];
static uint8_t label_row_blk[32];
static int32_t li_goto;
static struct ParseExprResult ret_val_lbl;
static uint8_t label_row_ret[32];
static int32_t ret_operand;
static int32_t li_ret;
static struct ParseExprResult ret_val_res;
static int return_ends_block;
static int32_t ret_ref;
static struct ast_Expr re;
static int32_t ret_ex_i;
static int32_t cond_ref_blk;
static struct ParseBlockResult block_res_blk;
static int32_t while_idx_blk;
static struct lexer_Lexer loop_cond_start;
static struct ParseExprResult expr_res;
static int32_t cond_ref;
static struct ParseBlockResult block_res;
static int32_t while_idx;
static int32_t init_ref;
static struct ParseExprResult expr_res_fi;
static int32_t cond_ref;
static struct ParseExprResult expr_res_fc;
static int32_t step_ref;
static struct ParseExprResult expr_res_fs;
static struct ParseBlockResult block_res;
static int32_t cond_expr_ref;
static struct ast_Expr ce;
static int32_t for_idx;
static struct ParseBlockResult block_res_def;
static int32_t def_i;
static int32_t cap_ref;
static struct ParseExprResult cap_res;
static struct ParseBlockResult block_res_wa;
static int32_t wa_pool_i;
static uint8_t reg_label_blk[64];
static int32_t reg_label_len_blk;
static struct ParseBlockResult block_res_reg;
static int32_t reg_pool_i;
static uint8_t unsafe_nm[64];
static struct ParseBlockResult block_res_unsafe;
static int32_t unsafe_pool_i;
static struct lexer_Lexer if_start;
static int32_t if_cond;
static int32_t if_then;
static int32_t if_else;
static int32_t if_pool_i;
static struct lexer_Lexer stmt_start;
static struct ParseExprResult expr_stmt_res;
static struct lexer_LexerResult rpeek_fe;
static struct lexer_LexerResult after_semi_blk;
static int32_t ex_pool_i;
static int32_t li_fix;
static int32_t ref;
static struct ast_Expr e;
static size_t arena_heap_bytes;
static struct lexer_Lexer lex;
static struct lexer_LexerResult r;
static struct lexer_Lexer lex_at_expr_start;
static int32_t ret_val;
static uint8_t * raw_arena;
static struct ast_ASTArena * heap_arena;
static struct ParseExprResult expr_out;
static struct ast_Expr e_read;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static uint8_t * pool;
static struct lexer_LexerResult r;
static struct ParseExprResult expr_tmp;
static int is_let;
static int32_t let_init_val;
static int32_t let_init_ref;
static int32_t let_ty_ref;
static int32_t is_discard_name;
static int32_t name_len;
static size_t name_start;
static uint8_t name_row[64];
static int32_t ni;
static int32_t zi;
static int let_omit_init;
static int cast_init_semi_done;
static int32_t init_handled;
static size_t bracket_start;
static int32_t arr_ref;
static struct ast_Expr ae0;
static int32_t er;
static struct ast_Expr ee;
static int32_t er;
static int arr_init_plain;
static int32_t reparsed_ref;
static int32_t rhs_ilen;
static size_t rhs_ident_start;
static struct lexer_Lexer expr_lex;
static int32_t str_ref;
static struct ast_Expr se;
static int32_t nlen;
static size_t q0;
static int32_t ri;
static int32_t wi;
static uint8_t c;
static uint8_t n;
static struct lexer_LexerResult after_semi_str;
static int32_t bool_ref;
static struct ast_Expr be;
static int32_t int_val_saved;
static size_t int_start;
static struct lexer_Lexer int_lex;
static int int_init_plain;
static size_t rhs_unary_start;
static struct lexer_Lexer unary_lex;
static size_t amp_start;
static struct lexer_Lexer amp_lex;
static struct lexer_Lexer if_lex;
static struct lexer_Lexer match_lex;
static size_t async_start;
static struct lexer_Lexer async_lex;
static struct lexer_LexerResult after_semi;
static struct lexer_Lexer lex_after_semi;
static struct lexer_Lexer lex_at_cur;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static int32_t depth;
static struct lexer_LexerResult r;
static struct shux_slice_uint8_t slice;
static int32_t depth;
static struct lexer_LexerResult r;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static int32_t i;
static size_t start;
static struct shux_slice_uint8_t slice;
static int32_t ko;
static int32_t ko;
static struct lexer_LexerResult nx;
static int32_t i;
static size_t start;
static int32_t i;
static size_t start;
static size_t start;
static int32_t i;
static int32_t i;
static struct OneFuncResult out_clean;
static struct OneFuncResult * out_ref;
static uint8_t dummy_name[64];
static struct OneFuncResult impl_snap;
static int return_type_is_bool;
static int32_t return_expr_ref_storage;
static size_t name_start;
static int32_t func_name_len_storage[1];
static struct lexer_LexerResult r;
static int32_t generic_n;
static int32_t plen;
static uint8_t pname_row[32];
static uint8_t * param_pool;
static int32_t param_idx;
static struct lexer_Lexer lex_before_type;
static int32_t type_ref_param;
static struct lexer_Lexer lex_before_ret;
static int32_t ret_type_ref;
static struct ast_Type rt;
static int32_t csr0;
static int32_t lsr;
static struct lexer_LexerResult r_peek;
static int stmt_tok_ready;
static size_t ret_id_start;
static struct lexer_Lexer ret_kw_lex;
static struct lexer_LexerResult r_ret_kw;
static int32_t n_before_mid;
static int32_t kw_back;
static struct lexer_Lexer lex_mid_let;
static int32_t push_mi;
static struct ParseBlockResult block_res_def_fn;
static int32_t def_idx_fn;
static struct ParseExprResult cap_res_fn;
static struct ParseBlockResult block_res_wa_fn;
static int32_t wa_idx_fn;
static uint8_t reg_nm_fn[64];
static int32_t reg_nlen_fn;
static struct ParseBlockResult block_res_reg_fn;
static int32_t reg_idx_fn;
static uint8_t unsafe_nm_fn[64];
static struct ParseBlockResult block_res_unsafe_fn;
static int32_t unsafe_idx_fn;
static struct lexer_LexerResult colon_fn;
static int32_t cond_ref_loop;
static struct ParseBlockResult block_res_loop;
static int32_t while_idx_loop;
static struct lexer_Lexer while_cond_start;
static struct ParseExprResult expr_res;
static int32_t cond_ref;
static struct ParseBlockResult block_res;
static int32_t while_idx;
static int32_t init_ref;
static struct ParseExprResult expr_res_fi;
static int32_t for_cond_ref;
static struct ParseExprResult expr_res_fc;
static int32_t step_ref;
static struct ParseExprResult expr_res_fs;
static struct ParseBlockResult block_res_f;
static int32_t cond_expr_ref;
static struct ast_Expr ce;
static int32_t for_idx;
static struct lexer_Lexer if_start_fn;
static int32_t if_cref;
static int32_t if_then_ref;
static int32_t if_else_ref;
static int32_t if_pool_idx;
static struct lexer_Lexer stmt_start;
static struct ParseExprResult expr_stmt_res;
static struct lexer_LexerResult after_semi;
static int32_t ex_i;
static struct lexer_Lexer match_tail_lex;
static struct ParseExprResult match_tail_res;
static size_t subj_start;
static struct lexer_Lexer match_subj_lex;
static struct ParseExprResult match_subj_res;
static struct lexer_Lexer match_ret_lex;
static struct ParseExprResult match_ret_res;
static struct lexer_Lexer rex_u_lex;
static struct ParseExprResult rex_u_res;
static struct lexer_Lexer if_lex;
static struct ParseExprResult if_res;
static struct lexer_Lexer rex_lex;
static struct ParseExprResult rex_out;
static struct lexer_Lexer lex_cond_start;
static struct ParseExprResult cond_res;
static int32_t ret_int_val;
static size_t ret_int_start;
static struct lexer_Lexer ret_int_lex;
static struct ParseExprResult ret_expr_res;
static struct ParseExprResult rex_add;
static struct lexer_Lexer rex_lex_ni;
static struct ParseExprResult rex_out_ni;
static int32_t clen;
static size_t cstart;
static uint8_t * binop_pool;
static int left_ok;
static int32_t ii;
static int right_ok;
static size_t match_back;
static struct lexer_Lexer match_lex_fix;
static struct ParseExprResult match_fix_res;
static struct lexer_Lexer ret_expr_lex;
static struct ParseExprResult ret_expr_res;
static struct lexer_Lexer ret_expr_lex_member;
static struct ParseExprResult ret_expr_res_member;
static struct lexer_Lexer ret_id_badlen_lex;
static struct ParseExprResult ret_id_badlen_res;
static int32_t ko;
static int32_t i;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static int32_t ei;
static int eq;
static int32_t j;
static int32_t slot;
static int32_t depth;
static size_t slen;
static struct lexer_LexerResult r;
static int32_t vlen;
static size_t vstart;
static uint8_t vb[64];
static int32_t nk;
static size_t ix;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static uint8_t * pool;
static int32_t p;
static uint8_t pname32[32];
static int32_t plen;
static int32_t pty;
static uint8_t empty64[64];
static int32_t ni;
static struct shux_slice_uint8_t slice;
static int32_t fi;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static int32_t k;
static int32_t ii;
static int same;
static int32_t k;
static int32_t ii;
static int same;
static int32_t k;
static int32_t ii;
static int same;
static int32_t nf;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static int32_t elem_tr_v;
static int32_t vec_ref;
static struct ast_Type tv;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct lexer_Lexer lex;
static int32_t main_idx;
static struct CollectImportsResult import_res;
static int32_t loop_count;
static struct lexer_Lexer iter_start;
static struct lexer_LexerResult r;
static struct lexer_Lexer current_tok_lex;
static int32_t func_is_async_storage[1];
static struct TrySkipAllowResult try_cfg_allow;
static int32_t ap_struct;
static int32_t ps_struct;
static int32_t pr_struct;
static int32_t pc_struct;
static int32_t pe_struct;
static int32_t allow_for_repr;
static int32_t nsl_before;
static int32_t pe_enum;
static int32_t nen_before;
static struct TrySkipAllowResult try_res;
static int32_t out_idx_storage[1];
static struct lexer_Lexer lex_at_function;
static uint8_t parse_into_empty64[64];
static struct OneFuncResult res;
static uint8_t empty64_lib_first[64];
static struct LibraryParseResult lib_first;
static int32_t is_main_storage[1];
static int32_t type_ref;
static struct ast_Type t_fb;
static int32_t expr_ref;
static struct ast_Expr e;
static int32_t rvi;
static uint8_t rvz;
static int allow_legacy_tail_expr;
static int32_t final_expr_ref;
static int32_t var_wrapped;
static int32_t mul_right_ref;
static struct ast_Expr mre;
static int32_t mul_ref;
static struct ast_Expr me;
static int32_t cond_ref;
static int32_t bool_type_ref;
static struct ast_Type bt;
static struct ast_Expr ce;
static int32_t then_ref;
static struct ast_Expr te;
static int32_t else_ref;
static struct ast_Expr ee;
static int32_t if_expr_ref;
static struct ast_Expr ie;
static uint8_t * res_pool;
static int32_t left_ref;
static int32_t left_param_type_ref;
static int32_t lpr;
static struct ast_Expr lpe;
static int32_t lk;
static uint8_t lz;
static int32_t right_ref;
static int32_t right_param_type_ref;
static int32_t rpr;
static struct ast_Expr rpe;
static int32_t rk;
static uint8_t rz;
static int32_t mul_left_ref;
static struct ast_Expr mle;
static int32_t mul_r_ref;
static struct ast_Expr mre;
static int32_t mul_ref;
static struct ast_Expr me;
static struct ast_Expr re;
static int32_t add_ref;
static struct ast_Expr ae;
static int32_t operand_ref;
static struct ast_Expr oe;
static int32_t neg_ref;
static struct ast_Expr ne;
static uint8_t * call_pool;
static int32_t callee_ref;
static struct ast_Expr ve;
static int32_t ck;
static uint8_t z;
static int32_t call_ref;
static struct ast_Expr ce;
static int32_t arg_i;
static int32_t arg_ref;
static struct ast_Expr ae;
static int32_t k;
static uint8_t z;
static int32_t block_ref;
static struct ast_Block b;
static int32_t wrapped_fe;
static int32_t n_while_pool;
static int32_t n_for_pool;
static int32_t n_if_pool;
static int32_t n_reg_pool;
static int32_t n_def_pool;
static int32_t ci2;
static int32_t li2;
static int32_t loop_i;
static int32_t for_i;
static int32_t if_oi;
static int32_t reg_oi;
static int32_t fin_ex;
static struct ast_Expr fe_dedup;
static int32_t fi;
static uint8_t * mod_pool;
static int32_t p;
static uint8_t pname32[32];
static int32_t out_idx_storage[1];
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct shux_slice_uint8_t slice;
static struct lexer_Lexer lex;
static int32_t main_idx;
static struct CollectImportsResult import_res;
static int32_t loop_count_buf;
static struct lexer_Lexer iter_start_buf;
static struct lexer_LexerResult r;
static struct lexer_Lexer current_tok_lex_buf;
static int32_t func_is_async_buf[1];
static struct TrySkipAllowResult try_cfg_allow_buf;
static struct lexer_Lexer lex_kw;
static int32_t ap_sb;
static int32_t ps_sb;
static int32_t pr_sb;
static int32_t pc_sb;
static int32_t pe_sb;
static int32_t allow_for_repr_buf;
static int32_t nsl_before_buf;
static int32_t pe_enum_buf;
static int32_t nen_before_buf;
static struct TypeAliasResult alias_res;
static int32_t pe_tl;
static int32_t ntl_before;
static struct TopLevelLetResult toplevel_res;
static struct TrySkipAllowResult try_res;
static int32_t out_idx_storage[1];
static struct lexer_Lexer lex_at_function_buf;
static uint8_t empty64_buf[64];
static struct OneFuncResult res;
static struct shux_slice_uint8_t slice_for_impl;
static uint8_t empty64_lib_buf_first[64];
static struct LibraryParseResult lib_buf_first;
static uint8_t skip_name[64] = {0};
static int32_t skip_nlen;
static int32_t is_main_storage[1];
static int32_t type_ref;
static struct ast_Type t_fb;
static int32_t expr_ref;
static struct ast_Expr e;
static int32_t rvi;
static uint8_t rvz;
static int allow_legacy_tail_expr2;
static int32_t final_expr_ref;
static int32_t var_wrapped;
static int32_t mul_right_ref;
static struct ast_Expr mre;
static int32_t mul_ref;
static struct ast_Expr me;
static int32_t cond_ref;
static int32_t bool_type_ref;
static struct ast_Type bt;
static struct ast_Expr ce;
static int32_t then_ref;
static struct ast_Expr te;
static int32_t else_ref;
static struct ast_Expr ee;
static int32_t if_expr_ref;
static struct ast_Expr ie;
static uint8_t * res_pool_buf;
static int32_t left_ref_buf;
static int32_t left_param_type_ref_buf;
static int32_t lpr_buf;
static struct ast_Expr lpe_buf;
static int32_t lk_buf;
static uint8_t lz_buf;
static int32_t right_ref_buf;
static int32_t right_param_type_ref_buf;
static int32_t rpr_buf;
static struct ast_Expr rpe_buf;
static int32_t rk_buf;
static uint8_t rz_buf;
static struct ast_Expr re_buf;
static int32_t add_ref_buf;
static struct ast_Expr ae_buf;
static uint8_t * call_pool_buf;
static int32_t callee_ref;
static struct ast_Expr ve;
static int32_t ck;
static uint8_t z;
static int32_t call_ref;
static struct ast_Expr ce;
static int32_t arg_i;
static int32_t arg_ref;
static struct ast_Expr ae;
static int32_t k;
static uint8_t z;
static int32_t block_ref;
static struct ast_Block b;
static int32_t wrapped_tail2;
static int32_t n_while_pool2;
static int32_t n_for_pool2;
static int32_t n_if_pool2;
static int32_t n_reg_pool2;
static int32_t n_def_pool2;
static int32_t ci2b;
static int32_t li2b;
static int32_t loop_ib;
static int32_t for_ib;
static int32_t if_oib;
static int32_t reg_oib;
static int32_t fin_ex2;
static struct ast_Expr fe_dedup2;
static int32_t func_ref;
static int32_t fi_mod;
static int32_t p_copy;
static uint8_t * mod_pool_buf;
static uint8_t pname32b[32];
static size_t parse_into_guard_pos;
static int32_t out_idx;
static int32_t out_idx_storage[1];
static uint8_t z;
static int32_t path_len;
static uint8_t path[32] = {47, 116, 109, 112, 47, 115, 104, 117, 95, 112, 97, 114, 115, 101, 95, 116, 101, 115, 116, 46, 115, 117, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static int32_t fd;
static uint8_t buf[128];
static ssize_t n;
static struct shux_slice_uint8_t sl;
static struct ParseResult res;
static uint8_t src[64] = {102, 117, 110, 99, 116, 105, 111, 110, 32, 109, 97, 105, 110, 40, 41, 58, 32, 105, 51, 50, 32, 123, 32, 114, 101, 116, 117, 114, 110, 32, 48, 59, 32, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static struct shux_slice_uint8_t sl;
static struct ParseResult res;
static void init_globals(void) {
  rewound = parser_rewind_lex_for_following_stmt(lex_in, r);
  rl = run_len;
  start = (end_pos - ((size_t)(rl)));
  ko = ((int32_t)(kind));
  lex_out = parser_rewind_lex_for_following_stmt(lex_in, r_in);
  lp_base = lex_at_token_from_result(r_in);
  back_lp = 2;
  lex_lp = (struct Lexer){ .pos = lexer_pos_before_run((lp_base.pos), back_lp), .line = ((r_in.tok).line), .col = ((r_in.tok).col) };
  r_lp = (struct LexerResult){ .next_lex = lex_lp, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  p = (ident_start - 6);
  p = (ident_start - 7);
  sep = (source)[(p + 6)];
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  _prime = (struct OneFuncResult){ .ok = 0, .next_lex = lexer_init(), .name = z64, .name_len = 0, .num_params = 0 };
  r_tail = (struct LexerResult){ .next_lex = lex_after_expr, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  lex_tail = lex_after_expr;
  _q2 = (struct OneFuncResult){ .num_consts = 0, .num_lets = 0 };
  _q3 = (struct OneFuncResult){ .has_if_expr = 0, .if_cond_true = 0, .if_then_val = 0, .if_else_val = 0, .if_cond_expr_ref = 0, .has_mul = 0, .mul_right_val = 0 };
  _q4 = (struct OneFuncResult){ .has_binop = 0, .binop_right_val = 0, .binop_left_param_idx = -(1), .binop_right_param_idx = -(1), .has_unary_neg = 0, .return_val = 0, .has_call_expr = 0, .call_callee_name = ccn };
  _q4b = (struct OneFuncResult){ .call_callee_len = 0, .return_var_name = rvn, .return_var_name_len = 0, .return_expr_ref = 0, .call_num_args = 0, .num_loops = 0 };
  _q5 = (struct OneFuncResult){ .num_for_loops = 0, .num_if_stmts = 0 };
  _q6 = (struct OneFuncResult){ .num_src_stmt_order = 0, .num_src_body_expr_stmts = 0, .func_return_type_ref = 0 };
  preserved_func_ret_ty = (dst.func_return_type_ref);
  ni = 0;
  rvni = 0;
  cci = 0;
  ni = 0;
  _w = (struct OneFuncResult){ .ok = 0, .next_lex = lex, .name = name64, .name_len = 0, .num_params = 0 };
  _w = (struct OneFuncResult){ .num_consts = 0, .num_lets = 0 };
  _w = (struct OneFuncResult){ .has_if_expr = 0, .if_cond_true = 0, .if_then_val = 0, .if_else_val = 0, .if_cond_expr_ref = 0, .has_mul = 0, .mul_right_val = 0 };
  _w = (struct OneFuncResult){ .has_binop = 0, .binop_right_val = 0, .binop_left_param_idx = -(1), .binop_right_param_idx = -(1), .has_unary_neg = 0, .return_val = 0, .has_call_expr = 0, .call_callee_name = name64 };
  _w = (struct OneFuncResult){ .call_callee_len = 0, .return_var_name_len = 0, .return_expr_ref = 0, .call_num_args = 0, .num_loops = 0 };
  _w = (struct OneFuncResult){ .num_for_loops = 0, .num_if_stmts = 0 };
  res = onefunc_scratch_empty();
  rvni = 0;
  _so = pipeline_onefunc_push_stmt_order(onefunc_result_pool_ptr(out), kind, idx);
  ref = ast_ast_arena_expr_alloc(arena);
  e = ast_ast_arena_expr_get(arena, ref);
  ref = ast_ast_arena_expr_alloc(arena);
  e = ast_ast_arena_expr_get(arena, ref);
  inner = ast_ast_arena_expr_get(arena, inner_ref);
  wrap = ast_ast_arena_expr_alloc(arena);
  rwe = ast_ast_arena_expr_get(arena, wrap);
  rtw = ast_ast_arena_type_get(arena, type_ref);
  slice = parser_slice_from_buf(data, len);
  scratch_sz = pipeline_sizeof_onefunc_result();
  scratch_raw = calloc(1, scratch_sz);
  temp = ((struct OneFuncResult *)(scratch_raw));
  lex_cur = lex_after_lbrace;
  block_ref = ast_ast_arena_block_alloc(arena);
  b = ast_ast_arena_block_get(arena, block_ref);
  block_prefix_lets = (b.num_lets);
  ci = 0;
  li = 0;
  r_peek_blk = (struct LexerResult){ .next_lex = lex_cur, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  r = r_peek_blk;
  stmt_tok_ready = 1;
  pb_break = 0;
  let_base_mid = (b.num_lets);
  kw_back_mid = 3;
  lex_mid_let = (struct Lexer){ .pos = lexer_pos_before_run(((r.next_lex).pos), kw_back_mid), .line = ((r.tok).line), .col = ((r.tok).col) };
  pi_mid = let_base_mid;
  label_len_blk = ((r.tok).ident_len);
  label_start_blk = (r.token_start);
  colon_blk = (struct LexerResult){ .next_lex = (r.next_lex), .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  goto_len_blk = ((r.tok).ident_len);
  goto_start_blk = (r.token_start);
  li_goto = pipeline_block_append_labeled(arena, block_ref, label_len_blk, 1, goto_len_blk, 0);
  ret_val_lbl = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  ret_operand = 0;
  li_ret = pipeline_block_append_labeled(arena, block_ref, label_len_blk, 0, 0, ret_operand);
  ret_val_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  return_ends_block = 0;
  ret_ref = ast_ast_arena_expr_alloc(arena);
  re = ast_ast_arena_expr_get(arena, ret_ref);
  ret_ex_i = pipeline_block_append_expr_stmt(arena, block_ref, ret_ref);
  cond_ref_blk = parser_alloc_true_bool_lit(arena);
  block_res_blk = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  while_idx_blk = pipeline_block_append_while(arena, block_ref, cond_ref_blk, (block_res_blk.block_ref));
  loop_cond_start = lex_cur;
  expr_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = loop_cond_start };
  cond_ref = (expr_res.expr_ref);
  block_res = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  while_idx = pipeline_block_append_while(arena, block_ref, cond_ref, (block_res.block_ref));
  init_ref = 0;
  expr_res_fi = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  cond_ref = 0;
  expr_res_fc = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  step_ref = 0;
  expr_res_fs = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  block_res = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  cond_expr_ref = ast_ast_arena_expr_alloc(arena);
  ce = ast_ast_arena_expr_get(arena, cond_expr_ref);
  for_idx = pipeline_block_append_for(arena, block_ref, init_ref, cond_ref, step_ref, (block_res.block_ref));
  block_res_def = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  def_i = pipeline_block_append_defer(arena, block_ref, (block_res_def.block_ref));
  cap_ref = 0;
  cap_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cur };
  block_res_wa = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  wa_pool_i = pipeline_block_append_with_arena(arena, block_ref, cap_ref, (block_res_wa.block_ref));
  reg_label_len_blk = ((r.tok).ident_len);
  block_res_reg = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  reg_pool_i = pipeline_block_append_region(arena, block_ref, &((reg_label_blk)[0]), reg_label_len_blk, (block_res_reg.block_ref));
  block_res_unsafe = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex_cur };
  unsafe_pool_i = pipeline_block_append_unsafe(arena, block_ref, (block_res_unsafe.block_ref));
  if_start = lex_at_token_from_result(r);
  if_cond = 0;
  if_then = 0;
  if_else = 0;
  if_pool_i = pipeline_block_append_if(arena, block_ref, if_cond, if_then, if_else);
  stmt_start = lex_at_token_from_result(r);
  expr_stmt_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = stmt_start };
  rpeek_fe = (struct LexerResult){ .next_lex = lex_cur, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  after_semi_blk = (struct LexerResult){ .next_lex = lex_cur, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  ex_pool_i = pipeline_block_append_expr_stmt(arena, block_ref, (expr_stmt_res.expr_ref));
  li_fix = 0;
  ref = ast_ast_arena_expr_alloc(arena);
  e = ast_ast_arena_expr_get(arena, ref);
  arena_heap_bytes = pipeline_sizeof_arena();
  lex = lexer_init();
  r = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  lex_at_expr_start = lex;
  ret_val = 0;
  raw_arena = calloc(1, arena_heap_bytes);
  heap_arena = ((struct ast_ASTArena *)(raw_arena));
  expr_out = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  e_read = ast_ast_arena_expr_get(heap_arena, (expr_out.expr_ref));
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  pool = onefunc_result_pool_ptr(out);
  r = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  expr_tmp = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  is_let = (((r.tok).kind) ==((token.TokenKind).TOKEN_LET));
  let_init_val = 0;
  let_init_ref = 0;
  let_ty_ref = 0;
  is_discard_name = 0;
  name_len = ((r.tok).ident_len);
  name_start = (r.token_start);
  ni = 0;
  zi = ni;
  let_omit_init = 0;
  cast_init_semi_done = 0;
  init_handled = 0;
  bracket_start = (r.token_start);
  arr_ref = ast_ast_arena_expr_alloc(arena);
  ae0 = ast_ast_arena_expr_get(arena, arr_ref);
  er = ast_ast_arena_expr_alloc(arena);
  ee = ast_ast_arena_expr_get(arena, er);
  er = parser_alloc_float_lit(arena, ((r.tok).float_val));
  arr_init_plain = ((((((((((r.tok).kind) ==((token.TokenKind).TOKEN_SEMICOLON)) || (((r.tok).kind) ==((token.TokenKind).TOKEN_LET))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_CONST))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_RETURN))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_IF))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_WHILE))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_FOR))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_RBRACE)));
  reparsed_ref = parse_body_let_bracket_compound_init_ref(arena, bracket_start, lex, source, &(lex), &(r));
  rhs_ilen = ((r.tok).ident_len);
  rhs_ident_start = (r.token_start);
  expr_lex = (struct Lexer){ .pos = rhs_ident_start, .line = ((r.tok).line), .col = ((r.tok).col) };
  str_ref = ast_ast_arena_expr_alloc(arena);
  se = ast_ast_arena_expr_get(arena, str_ref);
  nlen = ((r.tok).ident_len);
  q0 = (r.token_start);
  ri = 0;
  wi = 0;
  c = 0;
  n = 0;
  after_semi_str = (struct LexerResult){ .next_lex = (r.next_lex), .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  bool_ref = ast_ast_arena_expr_alloc(arena);
  be = ast_ast_arena_expr_get(arena, bool_ref);
  int_val_saved = ((r.tok).int_val);
  int_start = (r.token_start);
  int_lex = (struct Lexer){ .pos = int_start, .line = (lex.line), .col = (lex.col) };
  int_init_plain = ((((((((((r.tok).kind) ==((token.TokenKind).TOKEN_SEMICOLON)) || (((r.tok).kind) ==((token.TokenKind).TOKEN_LET))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_CONST))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_RETURN))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_IF))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_WHILE))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_FOR))) || (((r.tok).kind) ==((token.TokenKind).TOKEN_RBRACE)));
  rhs_unary_start = (r.token_start);
  unary_lex = (struct Lexer){ .pos = rhs_unary_start, .line = ((r.tok).line), .col = ((r.tok).col) };
  amp_start = (r.token_start);
  amp_lex = (struct Lexer){ .pos = amp_start, .line = ((r.tok).line), .col = ((r.tok).col) };
  if_lex = lex_at_token_from_result(r);
  match_lex = lex_at_token_from_result(r);
  async_start = (r.token_start);
  async_lex = (struct Lexer){ .pos = async_start, .line = ((r.tok).line), .col = ((r.tok).col) };
  after_semi = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  lex_after_semi = lex_at_token_from_result(after_semi);
  lex_at_cur = lex_at_token_from_result(r);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  depth = 1;
  r = lexer_next_buf(lex, data, len);
  slice = parser_slice_from_buf(data, len);
  depth = 1;
  r = lexer_next_buf(lex, data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  i = 0;
  start = (end_pos - ((size_t)(nlen)));
  slice = parser_slice_from_buf(data, len);
  ko = ((int32_t)(k));
  ko = ((int32_t)(k));
  nx = (struct LexerResult){ .next_lex = (r.next_lex), .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  i = 0;
  start = (end_pos - ((size_t)(nlen)));
  i = 0;
  start = (end_pos - ((size_t)(nlen)));
  start = (end_pos - ((size_t)(nlen)));
  i = 0;
  i = 0;
  out_clean = onefunc_alloc_wired_for_parse(lex);
  out_ref = out;
  impl_snap = onefunc_scratch_empty();
  return_type_is_bool = 0;
  return_expr_ref_storage = 0;
  name_start = ((size_t)(0));
  r = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  generic_n = 0;
  plen = ((r.tok).ident_len);
  param_pool = onefunc_result_pool_ptr(out);
  param_idx = pipeline_onefunc_append_param(param_pool, &((pname_row)[0]), plen, 0);
  lex_before_type = lex;
  type_ref_param = parse_type_ref_for_arena_into(arena, lex_before_type, source, &(lex));
  lex_before_ret = lex;
  ret_type_ref = parse_type_ref_for_arena_into(arena, lex_before_ret, source, &(lex));
  rt = ast_ast_arena_type_get(arena, ret_type_ref);
  csr0 = 0;
  lsr = 0;
  r_peek = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  stmt_tok_ready = 1;
  ret_id_start = (r.token_start);
  ret_kw_lex = (struct Lexer){ .pos = (ret_id_start - 7), .line = ((r.tok).line), .col = ((r.tok).col) };
  r_ret_kw = (struct LexerResult){ .next_lex = ret_kw_lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  n_before_mid = pipeline_onefunc_num_lets(onefunc_result_pool_ptr(out));
  kw_back = 3;
  lex_mid_let = (struct Lexer){ .pos = lexer_pos_before_run(((r.next_lex).pos), kw_back), .line = ((r.tok).line), .col = ((r.tok).col) };
  push_mi = n_before_mid;
  block_res_def_fn = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  def_idx_fn = pipeline_onefunc_append_defer(onefunc_result_pool_ptr(out), (block_res_def_fn.block_ref));
  cap_res_fn = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  block_res_wa_fn = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  wa_idx_fn = pipeline_onefunc_append_with_arena(onefunc_result_pool_ptr(out), (cap_res_fn.expr_ref), (block_res_wa_fn.block_ref));
  reg_nlen_fn = ((r.tok).ident_len);
  block_res_reg_fn = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  reg_idx_fn = pipeline_onefunc_append_region(onefunc_result_pool_ptr(out), &((reg_nm_fn)[0]), reg_nlen_fn, (block_res_reg_fn.block_ref));
  block_res_unsafe_fn = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  unsafe_idx_fn = pipeline_onefunc_append_unsafe(onefunc_result_pool_ptr(out), (block_res_unsafe_fn.block_ref));
  colon_fn = (struct LexerResult){ .next_lex = (r.next_lex), .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  cond_ref_loop = parser_alloc_true_bool_lit(arena);
  block_res_loop = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  while_idx_loop = pipeline_onefunc_append_while(onefunc_result_pool_ptr(out), cond_ref_loop, (block_res_loop.block_ref));
  while_cond_start = lex;
  expr_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = while_cond_start };
  cond_ref = (expr_res.expr_ref);
  block_res = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  while_idx = pipeline_onefunc_append_while(onefunc_result_pool_ptr(out), cond_ref, (block_res.block_ref));
  init_ref = 0;
  expr_res_fi = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  for_cond_ref = 0;
  expr_res_fc = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  step_ref = 0;
  expr_res_fs = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex };
  block_res_f = (struct ParseBlockResult){ .ok = 0, .block_ref = 0, .next_lex = lex };
  cond_expr_ref = ast_ast_arena_expr_alloc(arena);
  ce = ast_ast_arena_expr_get(arena, cond_expr_ref);
  for_idx = pipeline_onefunc_append_for(onefunc_result_pool_ptr(out), init_ref, for_cond_ref, step_ref, (block_res_f.block_ref));
  if_start_fn = lex_at_token_from_result(r);
  if_cref = 0;
  if_then_ref = 0;
  if_else_ref = 0;
  if_pool_idx = pipeline_onefunc_append_if(onefunc_result_pool_ptr(out), if_cref, if_then_ref, if_else_ref);
  stmt_start = lex_at_token_from_result(r);
  expr_stmt_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = stmt_start };
  after_semi = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  ex_i = pipeline_onefunc_push_body_expr_stmt(onefunc_result_pool_ptr(out), (expr_stmt_res.expr_ref));
  match_tail_lex = lex_at_token_from_result(r);
  match_tail_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = match_tail_lex };
  subj_start = (r.token_start);
  match_subj_lex = (struct Lexer){ .pos = (subj_start - 6), .line = ((r.tok).line), .col = ((r.tok).col) };
  match_subj_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = match_subj_lex };
  match_ret_lex = lex_at_token_from_result(r);
  match_ret_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = match_ret_lex };
  rex_u_lex = lex_at_token_from_result(r);
  rex_u_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = rex_u_lex };
  if_lex = lex_at_token_from_result(r);
  if_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = if_lex };
  rex_lex = lex_at_token_from_result(r);
  rex_out = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = rex_lex };
  lex_cond_start = lex;
  cond_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = lex_cond_start };
  ret_int_val = ((r.tok).int_val);
  ret_int_start = (r.token_start);
  ret_int_lex = (struct Lexer){ .pos = ret_int_start, .line = (lex.line), .col = (lex.col) };
  ret_expr_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = ret_int_lex };
  rex_add = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = ret_int_lex };
  rex_lex_ni = lex_at_token_from_result(r);
  rex_out_ni = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = rex_lex_ni };
  clen = ((r.tok).ident_len);
  cstart = (((r.next_lex).pos) - clen);
  binop_pool = onefunc_result_pool_ptr(out);
  left_ok = ((impl_snap.call_callee_len) ==pipeline_onefunc_param_name_len(binop_pool, 0));
  ii = 0;
  right_ok = (((r.tok).ident_len) ==pipeline_onefunc_param_name_len(binop_pool, 1));
  match_back = (cstart - 6);
  match_lex_fix = (struct Lexer){ .pos = match_back, .line = ((r.tok).line), .col = ((r.tok).col) };
  match_fix_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = match_lex_fix };
  ret_expr_lex = (struct Lexer){ .pos = cstart, .line = 1, .col = 1 };
  ret_expr_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = ret_expr_lex };
  ret_expr_lex_member = (struct Lexer){ .pos = cstart, .line = 1, .col = 1 };
  ret_expr_res_member = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = ret_expr_lex_member };
  ret_id_badlen_lex = lex_at_token_from_result(r);
  ret_id_badlen_res = (struct ParseExprResult){ .ok = 0, .expr_ref = 0, .next_lex = ret_id_badlen_lex };
  ko = ((int32_t)(kind));
  i = 0;
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  ei = 0;
  eq = 1;
  j = 0;
  slot = pipeline_module_enum_alloc(module);
  depth = 1;
  slen = ((size_t)(len));
  r = lexer_next_buf(lex, data, len);
  vlen = ((r.tok).ident_len);
  vstart = (r.token_start);
  nk = 0;
  ix = (vstart + ((size_t)(nk)));
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  pool = extern_parse_pool_ptr(res);
  p = 0;
  plen = pipeline_onefunc_param_name_len(pool, p);
  pty = pipeline_onefunc_param_type_ref(pool, p);
  ni = 0;
  slice = parser_slice_from_buf(data, len);
  fi = pipeline_module_func_alloc_slot(module);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  k = 0;
  ii = 0;
  same = 1;
  k = 0;
  ii = 0;
  same = 1;
  k = 0;
  ii = 0;
  same = 1;
  nf = pipeline_module_struct_layout_num_fields(module, k);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  elem_tr_v = pipeline_type_ensure_by_kind_ord(arena, elem_ord);
  vec_ref = 0;
  tv = ast_ast_arena_type_get(arena, vec_ref);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  lex = lexer_init();
  main_idx = -(1);
  import_res = (struct CollectImportsResult){ .lex = lex };
  loop_count = 0;
  iter_start = lex;
  r = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  current_tok_lex = lex;
  try_cfg_allow = (struct TrySkipAllowResult){ .lex = lex, .skipped = 0, ._pad = { 0 } };
  ap_struct = (module->pending_allow_padding);
  ps_struct = (module->pending_soa_struct);
  pr_struct = (module->pending_repr_c_struct);
  pc_struct = (module->pending_repr_compatible_struct);
  pe_struct = (module->pending_export);
  allow_for_repr = ap_struct;
  nsl_before = (module->num_struct_layouts);
  pe_enum = (module->pending_export);
  nen_before = (module->num_module_enums);
  try_res = (struct TrySkipAllowResult){ .lex = lex, .skipped = 0, ._pad = { 0 } };
  lex_at_function = current_tok_lex;
  res = onefunc_scratch_empty();
  lib_first = (struct LibraryParseResult){ .ok = 0, ._pad = { 0 }, .next_lex = lex_at_function, .name = empty64_lib_first, .name_len = 0, ._pad_tail = { 0 } };
  type_ref = (res.func_return_type_ref);
  t_fb = ast_ast_arena_type_get(arena, type_ref);
  expr_ref = ast_ast_arena_expr_alloc(arena);
  e = ast_ast_arena_expr_get(arena, expr_ref);
  rvi = 0;
  rvz = ((uint8_t)(0));
  allow_legacy_tail_expr = ((((res.has_final_expr) || (res.has_explicit_return_kw)) || ((res.return_expr_ref) !=0)) || ((res.return_var_name_len) > 0));
  final_expr_ref = 0;
  var_wrapped = parser_expr_wrap_in_return(arena, type_ref, final_expr_ref);
  mul_right_ref = ast_ast_arena_expr_alloc(arena);
  mre = ast_ast_arena_expr_get(arena, mul_right_ref);
  mul_ref = ast_ast_arena_expr_alloc(arena);
  me = ast_ast_arena_expr_get(arena, mul_ref);
  cond_ref = 0;
  bool_type_ref = ast_ast_arena_type_alloc(arena);
  bt = ast_ast_arena_type_get(arena, bool_type_ref);
  ce = ast_ast_arena_expr_get(arena, cond_ref);
  then_ref = ast_ast_arena_expr_alloc(arena);
  te = ast_ast_arena_expr_get(arena, then_ref);
  else_ref = ast_ast_arena_expr_alloc(arena);
  ee = ast_ast_arena_expr_get(arena, else_ref);
  if_expr_ref = ast_ast_arena_expr_alloc(arena);
  ie = ast_ast_arena_expr_get(arena, if_expr_ref);
  res_pool = onefunc_result_pool_ptr(&(res));
  left_ref = final_expr_ref;
  left_param_type_ref = pipeline_onefunc_param_type_ref(res_pool, (res.binop_left_param_idx));
  lpr = ast_ast_arena_expr_alloc(arena);
  lpe = ast_ast_arena_expr_get(arena, lpr);
  lk = 0;
  lz = ((uint8_t)(0));
  right_ref = 0;
  right_param_type_ref = pipeline_onefunc_param_type_ref(res_pool, (res.binop_right_param_idx));
  rpr = ast_ast_arena_expr_alloc(arena);
  rpe = ast_ast_arena_expr_get(arena, rpr);
  rk = 0;
  rz = ((uint8_t)(0));
  mul_left_ref = ast_ast_arena_expr_alloc(arena);
  mle = ast_ast_arena_expr_get(arena, mul_left_ref);
  mul_r_ref = ast_ast_arena_expr_alloc(arena);
  mre = ast_ast_arena_expr_get(arena, mul_r_ref);
  mul_ref = ast_ast_arena_expr_alloc(arena);
  me = ast_ast_arena_expr_get(arena, mul_ref);
  re = ast_ast_arena_expr_get(arena, right_ref);
  add_ref = ast_ast_arena_expr_alloc(arena);
  ae = ast_ast_arena_expr_get(arena, add_ref);
  operand_ref = ast_ast_arena_expr_alloc(arena);
  oe = ast_ast_arena_expr_get(arena, operand_ref);
  neg_ref = ast_ast_arena_expr_alloc(arena);
  ne = ast_ast_arena_expr_get(arena, neg_ref);
  call_pool = onefunc_result_pool_ptr(&(res));
  callee_ref = ast_ast_arena_expr_alloc(arena);
  ve = ast_ast_arena_expr_get(arena, callee_ref);
  ck = 0;
  z = ((uint8_t)(0));
  call_ref = ast_ast_arena_expr_alloc(arena);
  ce = ast_ast_arena_expr_get(arena, call_ref);
  arg_i = 0;
  arg_ref = ast_ast_arena_expr_alloc(arena);
  ae = ast_ast_arena_expr_get(arena, arg_ref);
  k = 0;
  z = ((uint8_t)(0));
  block_ref = ast_ast_arena_block_alloc(arena);
  b = ast_ast_arena_block_get(arena, block_ref);
  wrapped_fe = parser_expr_wrap_in_return(arena, type_ref, final_expr_ref);
  n_while_pool = pipeline_onefunc_num_whiles(onefunc_result_pool_ptr(&(res)));
  n_for_pool = pipeline_onefunc_num_fors(onefunc_result_pool_ptr(&(res)));
  n_if_pool = pipeline_onefunc_num_if_stmts(onefunc_result_pool_ptr(&(res)));
  n_reg_pool = pipeline_onefunc_num_regions(onefunc_result_pool_ptr(&(res)));
  n_def_pool = pipeline_onefunc_num_defers(onefunc_result_pool_ptr(&(res)));
  ci2 = 0;
  li2 = 0;
  loop_i = 0;
  for_i = 0;
  if_oi = 0;
  reg_oi = 0;
  fin_ex = pipeline_block_append_expr_stmt(arena, block_ref, final_expr_ref);
  fe_dedup = ast_ast_arena_expr_get(arena, final_expr_ref);
  fi = pipeline_module_func_alloc_slot(module);
  mod_pool = onefunc_result_pool_ptr(&(res));
  p = 0;
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  slice = parser_slice_from_buf(data, len);
  lex = lexer_init();
  main_idx = -(1);
  import_res = (struct CollectImportsResult){ .lex = lex };
  loop_count_buf = 0;
  iter_start_buf = lex;
  r = (struct LexerResult){ .next_lex = lex, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = 0, .col = 0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = 0 };
  current_tok_lex_buf = lex;
  try_cfg_allow_buf = (struct TrySkipAllowResult){ .lex = lex, .skipped = 0, ._pad = { 0 } };
  lex_kw = iter_start_buf;
  ap_sb = (module->pending_allow_padding);
  ps_sb = (module->pending_soa_struct);
  pr_sb = (module->pending_repr_c_struct);
  pc_sb = (module->pending_repr_compatible_struct);
  pe_sb = (module->pending_export);
  allow_for_repr_buf = ap_sb;
  nsl_before_buf = (module->num_struct_layouts);
  pe_enum_buf = (module->pending_export);
  nen_before_buf = (module->num_module_enums);
  alias_res = (struct TypeAliasResult){ .ok = 0, .next_lex = lex };
  pe_tl = (module->pending_export);
  ntl_before = (module->num_top_level_lets);
  toplevel_res = (struct TopLevelLetResult){ .ok = 0, .next_lex = lex };
  try_res = (struct TrySkipAllowResult){ .lex = lex, .skipped = 0, ._pad = { 0 } };
  lex_at_function_buf = current_tok_lex_buf;
  res = onefunc_scratch_empty();
  slice_for_impl = parser_slice_from_buf(data, len);
  lib_buf_first = (struct LibraryParseResult){ .ok = 0, ._pad = { 0 }, .next_lex = lex_at_function_buf, .name = empty64_lib_buf_first, .name_len = 0, ._pad_tail = { 0 } };
  skip_nlen = parse_peek_function_name_buf(lex_at_function_buf, data, len, &((skip_name)[0]));
  type_ref = (res.func_return_type_ref);
  t_fb = ast_ast_arena_type_get(arena, type_ref);
  expr_ref = ast_ast_arena_expr_alloc(arena);
  e = ast_ast_arena_expr_get(arena, expr_ref);
  rvi = 0;
  rvz = ((uint8_t)(0));
  allow_legacy_tail_expr2 = ((((res.has_final_expr) || (res.has_explicit_return_kw)) || ((res.return_expr_ref) !=0)) || ((res.return_var_name_len) > 0));
  final_expr_ref = 0;
  var_wrapped = parser_expr_wrap_in_return(arena, type_ref, final_expr_ref);
  mul_right_ref = ast_ast_arena_expr_alloc(arena);
  mre = ast_ast_arena_expr_get(arena, mul_right_ref);
  mul_ref = ast_ast_arena_expr_alloc(arena);
  me = ast_ast_arena_expr_get(arena, mul_ref);
  cond_ref = 0;
  bool_type_ref = ast_ast_arena_type_alloc(arena);
  bt = ast_ast_arena_type_get(arena, bool_type_ref);
  ce = ast_ast_arena_expr_get(arena, cond_ref);
  then_ref = ast_ast_arena_expr_alloc(arena);
  te = ast_ast_arena_expr_get(arena, then_ref);
  else_ref = ast_ast_arena_expr_alloc(arena);
  ee = ast_ast_arena_expr_get(arena, else_ref);
  if_expr_ref = ast_ast_arena_expr_alloc(arena);
  ie = ast_ast_arena_expr_get(arena, if_expr_ref);
  res_pool_buf = onefunc_result_pool_ptr(&(res));
  left_ref_buf = final_expr_ref;
  left_param_type_ref_buf = pipeline_onefunc_param_type_ref(res_pool_buf, (res.binop_left_param_idx));
  lpr_buf = ast_ast_arena_expr_alloc(arena);
  lpe_buf = ast_ast_arena_expr_get(arena, lpr_buf);
  lk_buf = 0;
  lz_buf = ((uint8_t)(0));
  right_ref_buf = 0;
  right_param_type_ref_buf = pipeline_onefunc_param_type_ref(res_pool_buf, (res.binop_right_param_idx));
  rpr_buf = ast_ast_arena_expr_alloc(arena);
  rpe_buf = ast_ast_arena_expr_get(arena, rpr_buf);
  rk_buf = 0;
  rz_buf = ((uint8_t)(0));
  re_buf = ast_ast_arena_expr_get(arena, right_ref_buf);
  add_ref_buf = ast_ast_arena_expr_alloc(arena);
  ae_buf = ast_ast_arena_expr_get(arena, add_ref_buf);
  call_pool_buf = onefunc_result_pool_ptr(&(res));
  callee_ref = ast_ast_arena_expr_alloc(arena);
  ve = ast_ast_arena_expr_get(arena, callee_ref);
  ck = 0;
  z = ((uint8_t)(0));
  call_ref = ast_ast_arena_expr_alloc(arena);
  ce = ast_ast_arena_expr_get(arena, call_ref);
  arg_i = 0;
  arg_ref = ast_ast_arena_expr_alloc(arena);
  ae = ast_ast_arena_expr_get(arena, arg_ref);
  k = 0;
  z = ((uint8_t)(0));
  block_ref = ast_ast_arena_block_alloc(arena);
  b = ast_ast_arena_block_get(arena, block_ref);
  wrapped_tail2 = parser_expr_wrap_in_return(arena, type_ref, final_expr_ref);
  n_while_pool2 = pipeline_onefunc_num_whiles(onefunc_result_pool_ptr(&(res)));
  n_for_pool2 = pipeline_onefunc_num_fors(onefunc_result_pool_ptr(&(res)));
  n_if_pool2 = pipeline_onefunc_num_if_stmts(onefunc_result_pool_ptr(&(res)));
  n_reg_pool2 = pipeline_onefunc_num_regions(onefunc_result_pool_ptr(&(res)));
  n_def_pool2 = pipeline_onefunc_num_defers(onefunc_result_pool_ptr(&(res)));
  ci2b = 0;
  li2b = 0;
  loop_ib = 0;
  for_ib = 0;
  if_oib = 0;
  reg_oib = 0;
  fin_ex2 = pipeline_block_append_expr_stmt(arena, block_ref, final_expr_ref);
  fe_dedup2 = ast_ast_arena_expr_get(arena, final_expr_ref);
  func_ref = ast_ast_arena_func_alloc(arena);
  fi_mod = pipeline_module_func_alloc_slot(module);
  p_copy = 0;
  mod_pool_buf = onefunc_result_pool_ptr(&(res));
  parse_into_guard_pos = (lex.pos);
  out_idx = main_idx;
  z = ((uint8_t)(0));
  path_len = 0;
  fd = std_fs_open(path);
  n = std_fs_read(fd, buf, 128);
  sl = parser_slice_from_buf(&((buf)[0]), ((int32_t)(n)));
  res = parse(sl);
  sl = parser_slice_from_buf(&((src)[0]), 35);
  res = parse(sl);
  i = 0;
  i = 0;
  l = lex;
  l = lex;
  p = 0;
  depth = 0;
  line0 = (l.line);
  col0 = (l.col);
  p = 0;
  depth = 0;
  expr_start = 0;
  expr_len = ((((int32_t)(p)) - ((int32_t)(expr_start))) - 1);
  ti = 0;
  enabled = 0;
  l2 = (struct Lexer){ .pos = p, .line = (l.line), .col = (l.col) };
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_CFG), .line = line0, .col = col0, .int_val = enabled, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  np = ((l.pos) + ((size_t)(10)));
  l2 = (struct Lexer){ .pos = np, .line = line0, .col = col0 };
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_REPR_C), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  np = ((l.pos) + ((size_t)(19)));
  l2 = (struct Lexer){ .pos = np, .line = line0, .col = col0 };
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_REPR_COMPATIBLE), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_SOA), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_ALLOC), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_ATTR_USED), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  line0 = (l.line);
  col0 = (l.col);
  l2 = l;
  l = lex;
  c = (data)[(l.pos)];
  l = skip_whitespace_and_comments(lex, data);
  attr_out = (struct LexerResult){ .next_lex = l, .tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = (l.line), .col = (l.col), .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 }, .token_start = ((size_t)(0)) };
  lex = l;
  cur = fval;
  exp_sign = 1;
  exp = 0;
  d = (data)[(lex.pos)];
  scale = 0.0;
  e = 0;
  c = (data)[(l.pos)];
  line0 = (l.line);
  col0 = (l.col);
  start = ((l.pos) + ((size_t)(1)));
  tok_eof = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  slen = ((int32_t)(((l.pos) - start)));
  tok_str = (struct Token){ .kind = ((token.TokenKind).TOKEN_STRING), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = slen };
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  len = ((l.pos) - start);
  tok = try_keyword(data, start, len, line0, col0);
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  ival = 0;
  hval = ((uint64_t)(0));
  hd = (data)[(l.pos)];
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_INT), .line = line0, .col = col0, .int_val = ((int64_t)(hval)), .float_val = 0.0, .ident = 0, .ident_len = 0 };
  d = (data)[(l.pos)];
  fval = ((double)(ival));
  frac = 0.0;
  d = (data)[(l.pos)];
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_FLOAT), .line = line0, .col = col0, .int_val = 0, .float_val = fval, .ident = 0, .ident_len = 0 };
  exp_sign = 1;
  exp = 0;
  d = (data)[(l.pos)];
  scale = 0.0;
  e = 0;
  fval = (((double)(ival)) * scale);
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_FLOAT), .line = line0, .col = col0, .int_val = 0, .float_val = fval, .ident = 0, .ident_len = 0 };
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_INT), .line = line0, .col = col0, .int_val = ival, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  fval = 0.0;
  frac = 0.0;
  d = (data)[(l.pos)];
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_FLOAT), .line = line0, .col = col0, .int_val = 0, .float_val = fval, .ident = 0, .ident_len = 0 };
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  tok = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  unk = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = line0, .col = col0, .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  l = skip_whitespace_and_comments(lex, data);
  t = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = (l.line), .col = (l.col), .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  t = (struct Token){ .kind = ((token.TokenKind).TOKEN_EOF), .line = (l.line), .col = (l.col), .int_val = 0, .float_val = 0.0, .ident = 0, .ident_len = 0 };
  c = (data)[(l.pos)];
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  len = ((l.pos) - start);
  tok = try_keyword(data, start, len, line0, col0);
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  ival = 0;
  hval = ((uint64_t)(0));
  hd = (data)[(l.pos)];
  d = (data)[(l.pos)];
  fval = ((double)(ival));
  frac = 0.0;
  d = (data)[(l.pos)];
  exp_sign = 1;
  exp = 0;
  d = (data)[(l.pos)];
  scale = 0.0;
  e = 0;
  fval = (((double)(ival)) * scale);
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  fval = 0.0;
  frac = 0.0;
  d = (data)[(l.pos)];
  start = (l.pos);
  line0 = (l.line);
  col0 = (l.col);
  sl = (uint8_t[]){ };
  lex = lexer_init();
  r = lexer_next(lex, sl);
  _tail = (struct Expr){ .kind = (ExprKind.EXPR_LIT), .resolved_type_ref = 0, .line = 0, .col = 0, .as_operand_ref = 0, .as_target_type_ref = 0, .call_resolved_func_index = -(1), .call_resolved_dep_index = -(1) };
  f0 = (struct Func){ .name = name0, .name_len = 0, .param_base = 0, .num_params = 0, .num_generic_params = 0, .return_type_ref = 0, .body_ref = 0, .body_expr_ref = 0, .is_extern = 0, .is_async = 0 };
  ref = 0;
  ref = 0;
  ref = 0;
  j = 0;
  sp = 0;
  cur = 0;
  par = 0;
  wb = 0;
  fb = 0;
  tb = 0;
  eb = 0;
  rgb = 0;
  i = 0;
  ref = 0;
}
extern size_t pipeline_sizeof_arena(void);
extern size_t pipeline_sizeof_onefunc_result(void);
extern struct ast_Module * pipeline_parser_get_match_module(void);
struct OneFuncResult onefunc_scratch_empty(void) {
  return (struct OneFuncResult){ .ok = 0, .next_lex = lexer_init(), .name = z64, .name_len = 0, .num_params = 0 };
}
